import { StudyPlanSubject } from "./types";

// In dit bestand kun je de links naar je avatars plaatsen.
// Vervang de onderstaande voorbeelden door de 20 links die je hebt.
// Zorg ervoor dat elke link een string is, tussen aanhalingstekens, en gescheiden door een komma.

// FIX: Added missing exports to resolve import errors.
export const defaultHomeLayout: string[] = ['agenda', 'files'];

export const allSubjects: string[] = [
  "nederlands", "engels", "wiskunde", "natuurkunde", "scheikunde", "biologie",
  "geschiedenis", "aardrijkskunde", "economie", "maatschappijleer",
  "frans", "duits", "latijn", "informatica", "kunst", "muziek",
  "lichamelijke_opvoeding", "ckv"
];

export const educationLevels: string[] = [
  "basisschool", "middelbare_school", "hogeschool_universiteit", "anders"
];

export const availableThemeColors: string[] = ['emerald', 'blue', 'rose', 'purple', 'pink', 'indigo', 'teal', 'amber'];

export const availableFonts: { id: string, name: string, className: string }[] = [
    { id: 'inter', name: 'Inter', className: 'font-inter' },
    { id: 'poppins', name: 'Poppins', className: 'font-poppins' },
    { id: 'lato', name: 'Lato', className: 'font-lato' },
    { id: 'roboto-slab', name: 'Roboto Slab', className: 'font-roboto-slab' },
    { id: 'lora', name: 'Lora', className: 'font-lora' },
];

export const subjectDisplayTranslations: { [lang: string]: { [key: string]: string } } = {
  nl: {
    // Subjects
    "nederlands": "Nederlands", "engels": "Engels", "wiskunde": "Wiskunde", "natuurkunde": "Natuurkunde",
    "scheikunde": "Scheikunde", "biologie": "Biologie", "geschiedenis": "Geschiedenis", "aardrijkskunde": "Aardrijkskunde",
    "economie": "Economie", "maatschappijleer": "Maatschappijleer", "frans": "Frans", "duits": "Duits",
    "latijn": "Latijn", "informatica": "Informatica", "kunst": "Kunst", "muziek": "Muziek",
    "lichamelijke_opvoeding": "Lichamelijke Opvoeding", "ckv": "CKV", "algemeen": "Algemeen",
    // Education levels
    "basisschool": "Basisschool", 
    "middelbare_school": "Middelbare School",
    "hogeschool_universiteit": "Hogeschool / Universiteit",
    "anders": "Anders"
  },
  en: {
    // Subjects
    "nederlands": "Dutch", "engels": "English", "wiskunde": "Mathematics", "natuurkunde": "Physics",
    "scheikunde": "Chemistry", "biologie": "Biology", "geschiedenis": "History", "aardrijkskunde": "Geography",
    "economie": "Economics", "maatschappijleer": "Social Studies", "frans": "French", "duits": "German",
    "latijn": "Latin", "informatica": "Informatics", "kunst": "Art", "muziek": "Music",
    "lichamelijke_opvoeding": "Physical Education", "ckv": "Cultural and Artistic Education", "algemeen": "General",
    // Education levels
    "basisschool": "Primary School",
    "middelbare_school": "High School",
    "hogeschool_universiteit": "College / University",
    "anders": "Other"
  }
};

export const translations: { [lang: string]: { [key: string]: string } } = {
    nl: {
        'tasks_for_today': 'Taken voor vandaag',
        'due_date': 'Vervaldatum',
        'recurring_daily': 'Dagelijks herhalen',
        'no_tasks_for_today': 'Geen taken voor vandaag. Goed bezig!',
        'todo_daily_refresh_note': 'De lijst wordt elke dag vernieuwd. Voltooide dagelijkse taken verschijnen opnieuw.',
        'error_reauth_failed': 'Herauthenticatie mislukt. Controleer je wachtwoord.',
        'reauth_modal_title': 'Authenticatie vereist',
        'reauth_modal_description': 'Voer je wachtwoord opnieuw in om door te gaan.',
        'password': 'Wachtwoord',
        'cancel_button': 'Annuleren',
        'confirm_delete_account_button': 'Ja, verwijder account',
        'reauth_modal_title_cleanup': 'Account opschonen bevestigen',
        'reauth_modal_description_cleanup': 'Voer je wachtwoord in om te bevestigen dat je alle gegevens wilt verwijderen.',
        'confirm_cleanup_account_button': 'Ja, schoon gegevens op',
        'reauth_modal_title_clear_calendar': 'Agenda leegmaken bevestigen',
        'reauth_modal_description_clear_calendar': 'Voer je wachtwoord in om te bevestigen dat je alle agenda-items wilt verwijderen.',
        'confirm_clear_calendar_button': 'Ja, maak agenda leeg',
        'clear_calendar_progress': 'Bezig met het leegmaken van je agenda...',
        'success_calendar_cleared': 'Je agenda is succesvol leeggemaakt.',
        'error_calendar_clear_failed': 'Het leegmaken van de agenda is mislukt.',
        'app_back_online_message': 'Je bent weer online.',
        'app_offline_message': 'Je bent momenteel offline.',
        'confirm_logout': 'Weet je zeker dat je wilt uitloggen?',
        'error_save_settings_failed': 'Kon instellingen niet opslaan.',
        'error_failed_to_save_admin_settings': 'Kon admin-instellingen niet opslaan.',
        'profile_picture_upload_success': 'Profielfoto succesvol bijgewerkt.',
        'error_profile_pic_upload_failed': 'Kon profielfoto niet uploaden.',
        'cleanup_account_progress': 'Bezig met het opschonen van je accountgegevens...',
        'success_account_cleaned': 'Je accountgegevens zijn succesvol opgeschoond.',
        'error_account_cleanup_failed': 'Het opschonen van het account is mislukt.',
        'deleting_account_progress': 'Account wordt verwijderd...',
        'success_account_deleted': 'Je account is succesvol verwijderd.',
        'error_account_deletion_failed': 'Het verwijderen van het account is mislukt.',
        'error_admin_login_failed': 'Inloggen als admin mislukt.',
        'guest_fallback_name': 'Gast',
        'error_account_disabled': 'Dit account is uitgeschakeld.',
        'streak_lost_notification_title': 'Streak verbroken!',
        'streak_lost_notification_text': 'Je had een streak van {count} dagen. Begin vandaag een nieuwe!',
        'error_profile_load_failed': 'Kon je profiel niet laden.',
        'success_logout': 'Je bent succesvol uitgelogd.',
        'share_link_copied': 'Link voor "{title}" gekopieerd!',
        'error_copy_share_link': 'Kon de link niet kopiëren.',
        'notifications_title': 'Notificaties',
        'logout_button': 'Uitloggen',
        'focus_session_complete': 'Focus sessie voltooid! Tijd voor een pauze.',
        'break_session_complete': 'Pauze is voorbij! Tijd om te focussen.',
        'feedback_reply_notification_title': 'Antwoord op je feedback',
        'feedback_reply_notification_text': 'Je hebt een antwoord ontvangen op je feedback over "{subject}".',
        'confirm_button': 'Bevestigen',
        'close_button': 'Sluiten',
        'calendar': 'Agenda',
        'extra_tools': 'Extra Tools',
        'settings': 'Instellingen',
        'feedback_support': 'Feedback & Support',
        'welcome_message': 'Welkom, {name}!',
        'streak_days': '{count} dagen streak',
        'my_subjects': 'Mijn Vakken',
        'my_files': 'Mijn Bestanden',
        'notes': 'Notities',
        'error_unknown': 'Er is een onbekende fout opgetreden.',
        'error_invalid_email': 'Ongeldig e-mailadres.',
        'error_invalid_credentials': 'Ongeldige inloggegevens.',
        'error_email_in_use': 'Dit e-mailadres is al in gebruik.',
        'error_weak_password': 'Wachtwoord moet minimaal 6 tekens lang zijn.',
        'error_fill_current_step': 'Vul alle velden van deze stap in.',
        'error_select_subjects_register': 'Selecteer ten minste één vak.',
        'error_fill_all_fields': 'Vul alle velden in.',
        'error_enter_email_for_reset': 'Voer je e-mailadres in om je wachtwoord opnieuw in te stellen.',
        'password_reset_sent': 'Een e-mail voor het opnieuw instellen van je wachtwoord is verzonden naar {email}.',
        'your_name': 'Jouw naam',
        'placeholder_name': 'bv. Jan Jansen',
        'email_address': 'E-mailadres',
        'placeholder_email': 'jouw@email.com',
        'placeholder_password': '••••••••',
        'school_name': 'Naam school',
        'class_name': 'Klas',
        'education_level': 'Onderwijsniveau',
        'select_level': 'Selecteer je niveau',
        'select_subjects': 'Selecteer je vakken',
        'select_your_avatar': 'Kies je avatar',
        'customize_ai_title': 'Personaliseer je AI Assistent',
        'bot_name_placeholder': 'Naam van je AI Bot',
        'select_bot_avatar': 'Kies een avatar voor je bot',
        'back_button': 'Terug',
        'next_button': 'Volgende',
        'saving': 'Opslaan...',
        'register_account': 'Account aanmaken',
        'register_title': 'Registreren',
        'login_title': 'Inloggen',
        'login_button': 'Inloggen',
        'login_in_progress': 'Inloggen...',
        'already_account': 'Heb je al een account? Log in',
        'no_account_register': 'Nog geen account? Registreer hier',
        'forgot_password': 'Wachtwoord vergeten?',
        'success_registration': 'Registratie succesvol! Controleer je e-mail om je account te verifiëren en log daarna in.',
        'your_subjects': 'Jouw Vakken',
        'search_subjects_placeholder': 'Zoek je vakken...',
        'profile_incomplete_message': 'Je hebt nog geen vakken geselecteerd.',
        'go_to_settings_message': 'Ga naar instellingen om je profiel compleet te maken.',
        'no_subjects_found_search': 'Geen vakken gevonden die overeenkomen met je zoekopdracht.',
        'todays_agenda_title': "Agenda van vandaag",
        'no_events_today': 'Geen evenementen voor vandaag.',
        'go_to_calendar': 'Ga naar de volledige agenda',
        'recent_files_title': 'Recente Bestanden',
        'recent_activities_title': 'Recente Activiteiten',
        'no_recent_files': 'Nog geen bestanden geüpload.',
        'no_recent_activity': 'Nog geen recente activiteit.',
        'view_button': 'Bekijk',
        'error_guest_action_not_allowed': 'Gasten kunnen deze actie niet uitvoeren.',
        'error_enter_file_title': 'Voer een titel in voor het bestand.',
        'error_select_file_to_upload': 'Selecteer een bestand om te uploaden.',
        'success_file_added': 'Bestand succesvol toegevoegd.',
        'error_add_file_failed': 'Kon bestand niet toevoegen: {message}',
        'error_select_files_delete': 'Selecteer bestanden om te verwijderen.',
        'confirm_delete_files': 'Weet je zeker dat je {count} bestand(en) wilt verwijderen?',
        'success_files_deleted': 'Bestand(en) succesvol verwijderd.',
        'error_delete_file_failed': 'Kon bestand niet verwijderen: {message}',
        'back_to_subjects': 'Terug naar vakken',
        'share_button': 'Delen',
        'add_file_section_title': 'Nieuw bestand toevoegen',
        'file_title_placeholder': 'Titel van het bestand',
        'file_description_placeholder': 'Beschrijving (optioneel)',
        'uploading': 'Uploaden...',
        'add_file_button': 'Bestand toevoegen',
        'admin_search_placeholder': 'Zoek op naam of e-mail...',
        'select_files_button': 'Selecteren',
        'no_files_found': 'Geen bestanden gevonden voor dit vak.',
        'calendar_title': 'Agenda',
        'today': 'Vandaag',
        'add_event': 'Nieuw',
        'no_events_day': 'Geen afspraken op deze dag.',
        'edit_event': 'Afspraak bewerken',
        'event_title': 'Titel',
        'event_description': 'Beschrijving (optioneel)',
        'event_test': 'Toets',
        'event_presentation': 'Presentatie',
        'event_homework': 'Huiswerk',
        'event_oral': 'Mondeling',
        'event_other': 'Anders',
        'event_work': 'Werk',
        'event_school': 'School',
        'event_study_plan': 'Studieplan Taak',
        'save_note_button': 'Opslaan',
        'add_event_button': 'Toevoegen',
        'event_subject': 'Vak',
        'event_type': 'Type',
        'delete_event_confirm': 'Weet je zeker dat je "{title}" wilt verwijderen?',
        'success_event_updated': 'Afspraak succesvol bijgewerkt.',
        'success_event_added': 'Afspraak succesvol toegevoegd.',
        'settings_title': 'Instellingen',
        'settings_account_section': 'Account',
        'settings_appearance_section': 'Weergave',
        'settings_privacy_section': 'Privacy & Gegevens',
        'settings_help_info_section': 'Help & Info',
        'profile_section': 'Profiel',
        'profile_picture_current': 'Huidige profielfoto',
        'profile_picture_upload_label': 'Wijzig je profielfoto',
        'change_avatar_button': 'Avatar wijzigen',
        'add_custom_subject': 'Eigen vak toevoegen',
        'custom_subject_placeholder': 'Naam van je vak',
        'error_subject_empty': 'Vaknaam mag niet leeg zijn.',
        'error_subject_exists': 'Dit vak bestaat al.',
        'confirm_remove_subjects_warning': 'Als je vakken deselecteert, worden gerelateerde gegevens zoals bestanden en notities mogelijk niet meer weergegeven. Weet je het zeker?',
        'success_settings_saved': 'Instellingen succesvol opgeslagen.',
        'save_profile_info_button': 'Profiel opslaan',
        'password_reset_section_title': 'Wachtwoord opnieuw instellen',
        'password_reset_section_description': 'Stuur een e-mail naar {email} met instructies om je wachtwoord opnieuw in te stellen.',
        'send_reset_email_button': 'Stuur reset e-mail',
        'error_password_reset_failed': 'Kon wachtwoord reset e-mail niet versturen.',
        'danger_zone_title': 'Gegevensbeheer',
        'cleanup_account_section_title': 'Accountgegevens opschonen',
        'cleanup_account_section_description': 'Dit verwijdert al je persoonlijke gegevens (bestanden, notities, taken, etc.) maar behoudt je account. Deze actie kan niet ongedaan worden gemaakt.',
        'cleanup_account_button': 'Gegevens opschonen',
        'clear_calendar_section_title': 'Agenda leegmaken',
        'clear_calendar_section_description': 'Dit verwijdert permanent alle afspraken uit je agenda. Deze actie kan niet ongedaan worden gemaakt.',
        'clear_calendar_button': 'Agenda leegmaken',
        'delete_account_section_title': 'Account permanent verwijderen',
        'delete_account_section_description': 'Dit zal je account en al je gegevens permanent verwijderen. Deze actie kan niet ongedaan worden gemaakt.',
        'delete_account_button': 'Account verwijderen',
        'choose_theme': 'Kies een thema',
        'font_preference': 'Lettertypevoorkeur',
        'default': 'Standaard',
        'language_preference': 'Taalvoorkeur',
        'dutch': 'Nederlands',
        'english': 'English',
        'home_layout_title': 'Startpagina Indeling',
        'home_layout_description': 'Sleep de widgets om de volgorde op je startpagina aan te passen.',
        'widget_subjects': 'Mijn Vakken',
        'widget_agenda': 'Agenda Vandaag',
        'widget_files': 'Recente Bestanden',
        'notifications_settings_title': 'Notificatie-instellingen',
        'enable_notifications': 'Notificaties inschakelen',
        'privacy_policy_content': 'Jouw privacy is voor ons van het grootste belang. Alle gegevens die je invoert in StudyBox, zoals je bestanden, notities, agenda-items en persoonlijke informatie, worden versleuteld en veilig opgeslagen op onze servers. We gebruiken deze gegevens uitsluitend om de functionaliteit van de app te waarborgen en jouw ervaring te personaliseren. We zullen je gegevens nooit verkopen, delen of op een andere manier openbaar maken aan derden zonder jouw expliciete toestemming. Je hebt te allen tijde de controle over je eigen data en kunt via de gevarenzone-instellingen je gegevens opschonen of je volledige account verwijderen. Voor meer gedetailleerde informatie over ons gegevensbeleid, neem contact met ons op via de support-opties.',
        'app_info': 'Over de app',
        'faq': 'Veelgestelde vragen',
        'version': 'Versie',
        'copyright': 'Alle rechten voorbehouden.',
        'pomodoros': "Pomodoro's",
        'todo_list': 'Takenlijst',
        'flashcards': 'Flashcards',
        'select_a_subject_first': 'Selecteer eerst een vak',
        'sets_for_subject': 'Sets voor {subject}',
        'set_name_placeholder': 'Naam van de nieuwe set',
        'no_sets_found': 'Geen sets gevonden voor dit vak. Maak een nieuwe aan!',
        'no_subjects_flashcards': 'Je hebt nog geen vakken voor je flashcards.',
        'go_to_settings_flashcards': 'Ga naar instellingen om vakken toe te voegen en te beginnen!',
        'cards_in_set': '{count} kaarten',
        'manage_cards': 'Beheren',
        'choose_study_mode': 'Kies een studeermodus',
        'reset_srs_progress': 'Voortgang resetten',
        'study_mode_learn_title': 'Leren (SRS)',
        'study_mode_learn_desc': 'Gebruikt Spaced Repetition om je te helpen efficiënt te leren voor de lange termijn.',
        'study_mode_cram_title': 'Stampen',
        'study_mode_cram_desc': 'Ga snel door alle kaarten heen. Ideaal voor een snelle herhaling vlak voor een toets.',
        'study_mode_mc_title': 'Multiple Choice',
        'study_mode_mc_desc': 'Test je kennis met meerkeuzevragen, willekeurig gegenereerd uit je set.',
        'study_mode_vocab_title': 'Woordenlijst',
        'study_mode_vocab_desc': 'Typ zelf het antwoord. De AI controleert op synoniemen en alternatieve correcte antwoorden.',
        'start_session': 'Start sessie',
        'back_to_sets': 'Terug naar sets',
        'add_flashcard': 'Flashcards beheren',
        'question': 'Vraag (voorkant)',
        'answer': 'Antwoord (achterkant)',
        'add_more_rows': '5 rijen toevoegen',
        'flashcard_added_success': 'Flashcards succesvol opgeslagen.',
        'error_empty_flashcard': 'Voer ten minste één vraag en antwoord in.',
        'next_card': 'Volgende kaart',
        'cards_to_go': '{count} te gaan',
        'cards_to_go_counter': '{current} / {total}',
        'show_answer': 'Toon antwoord',
        'feedback_again': 'Opnieuw',
        'feedback_good': 'Goed',
        'no_flashcards_found': 'Geen flashcards gevonden',
        'all_cards_learned_title': 'Alles geleerd!',
        'all_cards_learned_desc': 'Goed gedaan! Je hebt alle kaarten voor deze sessie bestudeerd. Kom later terug voor herhaling.',
        'choose_other_method_button': 'Kies andere modus',
        'reset_and_start_over_button': 'Reset & Herstart',
        'session_complete': 'Sessie voltooid!',
        'your_score': 'Je score: {correct} / {total}',
        'your_grade': 'Jouw Cijfer',
        'well_done_message': 'Goed gedaan! Blijf oefenen.',
        'focus_session': 'Focus',
        'break_session': 'Pauze',
        'Focusing on:': 'Focus op:',
        'no_specific_task_option': 'Geen taak geselecteerd',
        'set_added_success': 'Set succesvol aangemaakt.',
        'confirm_delete_set': 'Weet je zeker dat je de set "{name}" en alle bijbehorende kaarten wilt verwijderen?',
        'set_deleted_success': 'Set succesvol verwijderd.',
        'error_empty_set_name': 'Naam van de set mag niet leeg zijn.',
        'reset_srs_confirm': 'Weet je zeker dat je de leervoortgang (SRS) voor deze set wilt resetten?',
        'error_flashcard_set_min_cards': 'Deze modus vereist minimaal 2 kaarten in de set.',
        'error_vocab_set_min_cards': 'Deze modus vereist minimaal 1 kaart in de set.',
        'loading_cards': 'Kaarten laden...',
        'error_failed_to_load_cards': 'Kon flashcards niet laden.',
        'error_failed_to_load_sets': 'Kon sets niet laden.',
        'all_subjects_option': 'Alle vakken',
        'add_note_button': 'Nieuwe notitie',
        'edit_note': 'Notitie bewerken',
        'add_note_title_placeholder': 'Titel',
        'add_note_content_placeholder': 'Begin hier met typen...',
        'note_updated_success': 'Notitie succesvol bijgewerkt.',
        'note_added_success': 'Notitie succesvol toegevoegd.',
        'error_empty_note_title': 'Titel mag niet leeg zijn.',
        'confirm_delete_note': 'Weet je zeker dat je deze notitie wilt verwijderen?',
        'note_deleted_success': 'Notitie succesvol verwijderd.',
        'set_reminder_title': 'Herinnering instellen voor: {task}',
        'reminder_date': 'Datum',
        'reminder_time': 'Tijd',
        'save_reminder_button': 'Herinnering opslaan',
        'remove_reminder_button': 'Verwijder herinnering',
        'task_reminder_title': 'Taakherinnering',
        'error_failed_to_load_tasks': 'Kon taken niet laden.',
        'add_task_placeholder': 'Voeg een nieuwe taak toe...',
        'add_task_button': 'Toevoegen',
        'no_tasks_found': 'Geen taken gevonden. Voeg er een toe om te beginnen!',
        'task_added_success': 'Taak succesvol toegevoegd.',
        'task_updated_success': 'Taakstatus bijgewerkt.',
        'confirm_delete_task': 'Weet je zeker dat je deze taak wilt verwijderen?',
        'task_deleted_success': 'Taak succesvol verwijderd.',
        'notifications_denied_error': 'Notificaties zijn geblokkeerd. Schakel ze in via je browserinstellingen.',
        'notifications_denied_prompt': 'Je hebt geen toestemming gegeven voor notificaties. De herinnering wordt niet getoond.',
        'error_empty_task': 'Taak mag niet leeg zijn.',
        'grade_calculator_title': 'Cijfercalculator',
        'grade_name_placeholder': 'Naam toets (optioneel)',
        'grade': 'Cijfer',
        'weight': 'Weging (%)',
        'add_grade': 'Cijfer toevoegen',
        'current_average': 'Je huidige gemiddelde:',
        'goal_calculator_title': 'Doelcalculator',
        'desired_average': 'Gewenst gemiddelde',
        'future_exam_weight': 'Weging toekomstige toets (%)',
        'calculate_needed_grade': 'Bereken benodigd cijfer',
        'goal_easy_message': 'Je staat al hoger dan je doel. Goed bezig!',
        'goal_impossible_message': 'Het is wiskundig onmogelijk om je doel te halen. Het hoogst haalbare is...',
        'grade_needed_message': 'Je moet een **{grade}** halen om een **{desired_average}** te staan.',
        'admin_dashboard': 'Admin Dashboard',
        'users': 'Gebruikers',
        'broadcasts': 'Aankondigingen',
        'admin_feedback_dashboard': 'Feedback',
        'loading_data': 'Gegevens laden...',
        'last_login': 'Laatste login',
        'status': 'Status',
        'actions': 'Acties',
        'active': 'Actief',
        'disabled': 'Uitgeschakeld',
        'enable_user': 'Activeer gebruiker',
        'disable_user': 'Deactiveer gebruiker',
        'refresh_data': 'Vernieuwen',
        'confirm_disable_user': 'Weet je zeker dat je gebruiker {name} wilt deactiveren?',
        'confirm_enable_user': 'Weet je zeker dat je gebruiker {name} wilt activeren?',
        'user_status_updated': 'Gebruikersstatus succesvol bijgewerkt.',
        'error_user_status_update': 'Kon gebruikersstatus niet bijwerken.',
        'send_broadcast': 'Aankondiging versturen',
        'broadcast_title_placeholder': 'Titel',
        'broadcast_message_placeholder': 'Typ hier je bericht...',
        'sending': 'Verzenden...',
        'send_message_button': 'Verstuur bericht',
        'error_broadcast_empty': 'Titel en bericht mogen niet leeg zijn.',
        'broadcast_success': 'Aankondiging succesvol verstuurd.',
        'error_broadcast_failed': 'Kon aankondiging niet versturen.',
        'past_broadcasts': 'Eerdere aankondigingen',
        'delete_all_broadcasts': 'Alles verwijderen',
        'no_past_broadcasts': 'Geen eerdere aankondigingen.',
        'confirm_delete_all_broadcasts_and_notifications': 'Weet je zeker dat je ALLE aankondigingen en de bijbehorende notificaties voor alle gebruikers wilt verwijderen? Dit kan niet ongedaan worden gemaakt.',
        'all_broadcasts_deleted': 'Alle aankondigingen en notificaties zijn verwijderd.',
        'error_deletion_failed': 'Verwijderen mislukt.',
        'from': 'Van',
        'submitted_on': 'Ingediend op',
        'status_new': 'Nieuw',
        'status_replied': 'Beantwoord',
        'reply_to_feedback': 'Antwoord op feedback',
        'your_reply_placeholder': 'Typ je antwoord...',
        'send_reply_button': 'Verstuur antwoord',
        'reply_sent_success': 'Antwoord succesvol verstuurd.',
        'error_reply_failed': 'Kon antwoord niet versturen.',
        'admin_select_feedback': 'Selecteer een feedbackbericht om de details te bekijken en te beantwoorden.',
        'admin_streak_leaderboard': 'Streak Leaderboard',
        'no_streak_users': 'Geen gebruikers met een actieve streak.',
        'admin_appearance_settings': 'Weergave Instellingen (Admin)',
        'admin_security_settings': 'Beveiligingsinstellingen',
        'admin_pin_toggle_label': 'PIN-beveiliging bij opstarten inschakelen',
        'admin_pin_verify_title': 'PIN verificatie',
        'admin_pin_verify_desc': 'Om deze instelling te wijzigen, moet je de beveiligingsvraag beantwoorden.',
        'admin_pin_secret_question': 'What is the best anime?',
        'admin_pin_answer_placeholder': 'Jouw antwoord',
        'admin_pin_error_incorrect': 'Incorrect antwoord.',
        'no_avatar_option': 'Geen avatar',
        'avatar_selection_title': 'Kies je avatar',
        'save_avatar_button': 'Opslaan',
        'back': 'Terug',
        'mark_all_as_read': 'Markeer alles als gelezen',
        'confirm_clear_all_notifications': 'Weet je zeker dat je alle notificaties wilt verwijderen?',
        'notifications_cleared': 'Notificaties gewist.',
        'no_notifications': 'Je hebt geen nieuwe notificaties.',
        'no_notifications_disabled_title': 'Notificaties zijn uitgeschakeld',
        'no_notifications_disabled_text': 'Je ontvangt geen meldingen. Je kunt dit wijzigen in de instellingen.',
        'intro_step1_title': 'Welkom bij StudyBox!',
        'intro_step1_text': 'Jouw persoonlijke assistent voor school. Organiseer je bestanden, agenda en notities op één plek.',
        'intro_step2_title': 'Beheer je Agenda',
        'intro_step2_text': 'Voeg toetsen, huiswerk en deadlines toe. Mis nooit meer een belangrijke datum!',
        'intro_step3_title': 'Krachtige Tools',
        'intro_step3_text': 'Gebruik de studietimer, takenlijst en flashcards om je productiviteit te verhogen.',
        'intro_step4_title': 'Kies je Stijl',
        'intro_step4_text': 'Geef je dashboard een uniek uiterlijk dat bij jouw stijl past met verschillende thema\'s en avatars.',
        'intro_step5_title': 'Klaar om te Beginnen?',
        'intro_step5_text': 'Laten we je account aanmaken en je schoolleven organiseren!',
        'intro_finish_button': 'Aan de slag',
        'verify_email_title': 'Verifieer je e-mailadres',
        'verify_email_instructions': 'We hebben een verificatielink gestuurd naar {email}. Klik op de link om je account te activeren.',
        'verify_email_spam_check': 'Controleer ook je spamfolder als je de e-mail niet kunt vinden.',
        'verify_email_continue_button': 'Ik heb mijn e-mail geverifieerd',
        'verify_email_resend_button': 'Stuur opnieuw',
        'email_sent': 'E-mail verzonden!',
        'feedback_title': 'Feedback & Support',
        'feedback_subtitle': 'Heb je een vraag, een suggestie of een probleem gevonden? Laat het ons weten!',
        'feedback_subject_placeholder': 'Onderwerp',
        'feedback_message_placeholder': 'Jouw bericht...',
        'send_feedback_button': 'Verstuur',
        'feedback_sent_success': 'Bedankt voor je feedback!',
        'error_feedback_failed': 'Kon feedback niet versturen.',
        'your_feedback_history': 'Jouw feedbackgeschiedenis',
        'no_feedback_history': 'Je hebt nog geen feedback verzonden.',
        'error_email_not_verified': 'Je e-mailadres is nog niet geverifieerd. Controleer je e-mail en klik op de verificatielink.',
        'ai_importer_title': "AI Import",
        'ai_importer_description': "Plak of typ je rooster hieronder. De AI zal automatisch de afspraken voor je aanmaken. Voorbeeld: 'Volgende week maandag wiskunde om 10:00 en dinsdag een toets Engels.'",
        'analyze_button': "Analyseer Rooster",
        'analyzing': "Analyseren...",
        'review_schedule': "Controleer de Gevonden Afspraken",
        'import_for_weeks': "Importeer voor",
        'weeks': "weken",
        'days_to_import': "Dagen om te importeren",
        'import_button': "Importeer in Agenda",
        'ai_no_events_found': "De AI kon geen afspraken vinden. Probeer de tekst duidelijker te maken.",
        'importing': "Importeren...",
        'import_success': "{count} afspraken succesvol geïmporteerd!",
        'import_error': "Fout bij het importeren van afspraken.",
        'ai_parsing_error': "Fout bij het analyseren van de tekst. Controleer het formaat en probeer het opnieuw.",
        'day_monday': 'Maandag', 'day_tuesday': 'Dinsdag', 'day_wednesday': 'Woensdag',
        'day_thursday': 'Donderdag', 'day_friday': 'Vrijdag', 'day_saturday': 'Zaterdag', 'day_sunday': 'Zondag',
        'edit_text_button': 'Tekst bewerken',
        'import_and_close_button': 'Importeer en sluit',
        'progress': 'Voortgang',
        'time_spent_per_subject': 'Tijd Besteed per Vak',
        'content_per_subject': 'Inhoud per Vak',
        'total_study_time': 'Totale Studietijd',
        'total_items': 'Totaal Aantal Items',
        'hours': 'uur',
        'items': 'items',
        'no_data_for_chart': 'Nog niet genoeg gegevens om een grafiek te tonen.',
        'event_type_distribution': 'Verdeling Soort Afspraken',
        'study_planner': 'Studieplanner',
        'planner_create_your_schedule': 'Maak je persoonlijke leerschema',
        'planner_subject': 'Vak',
        'planner_select_subject': 'Kies een vak',
        'planner_topic': 'Onderwerp van de toets',
        'planner_topic_placeholder': 'bv. De Koude Oorlog',
        'planner_amount': 'Hoeveelheid leerstof',
        'planner_amount_placeholder': 'bv. Hoofdstuk 1-4, 50 pagina\'s',
        'planner_test_date': 'Datum van de toets',
        'planner_generate_button': 'Genereer Schema',
        'planner_generating': 'Schema wordt gemaakt...',
        'planner_error_title': 'Oeps, er ging iets mis',
        'planner_error_text': 'De AI kon geen schema genereren. Probeer je invoer specifieker te maken of probeer het later opnieuw.',
        'planner_result_title': 'Jouw Leerschema voor {subject}',
        'planner_start_over': 'Opnieuw beginnen',
        'planner_study_day': 'Leerdag',
        'planner_task': 'Taak',
        'planner_tip': 'Tip',
        'error_all_fields_required': 'Vul alle velden in om een schema te genereren.',
        'study_planner_title': 'Mijn Studieplanners',
        'create_new_plan': 'Nieuw Plan Maken',
        'plan_for_date': 'Plan voor {date}',
        'delete_plan_confirm': 'Weet je zeker dat je dit studieplan wilt verwijderen?',
        'confirm_delete_plans': 'Weet je zeker dat je {count} plan(nen) wilt verwijderen?',
        'plan_deleted_success': 'Studieplan succesvol verwijderd.',
        'plan_subjects': 'Vakken',
        'plan_test_date': 'Datum Toets',
        'add_subject_button': 'Vak Toevoegen',
        'remove_subject_button': 'Verwijder Vak',
        'creating_plan': 'Plan wordt gemaakt...',
        'plan_created_success': 'Je persoonlijke studieplan is gemaakt!',
        'no_plans_yet': 'Je hebt nog geen studieplanners gemaakt.',
        'no_plans_cta': 'Klik op "Nieuw Plan Maken" om te beginnen!',
        'plan_title': 'Titel van Plan',
        'plan_title_placeholder': 'bv. Voorbereiding Eindexamens',
        'view_plan': 'Bekijk Plan',
        'hide_plan': 'Verberg Plan',
        'subject': 'Vak',
        'select_button': 'Selecteren',
        'select_all_button': 'Alles selecteren',
        'delete_selected_button': 'Verwijder geselecteerde',
        'back_to_subjects_selection': 'Terug naar vakken',
        'ai_chat': 'AI Chat',
        'ai_chat_placeholder': 'Vraag iets of geef een opdracht...',
        'ai_chat_welcome': 'Hallo {userName}! Ik ben {botName}, je persoonlijke studie-assistent. Hoe kan ik je vandaag helpen?',
        'chat_history_title': 'Chatgeschiedenis',
        'new_chat': 'Nieuwe Chat',
        'error_generating_title': 'Kon geen titel genereren.',
        'in_progress_badge': 'NU BEZIG',
        'tasks_completed': 'Voltooide Taken',
        'study_time_minutes': 'Studieminuten',
        'flashcards_created': 'Gemaakte Flashcards',
        'todays_events': 'Afspraken Vandaag',
        'flashcard_ai_modal_title': "Kaarten Genereren met AI",
        'flashcard_ai_modal_desc': "Plak of typ je notities. De AI zet ze om in vraag-en-antwoord kaarten.",
        'flashcard_ai_placeholder': "Begrip 1: Uitleg 1\nTerm 2 - Definitie 2",
        'generate_button': "Genereer",
        'generating': "Genereren...",
        'save_all_cards': "Alles Opslaan",
        'settings_sync_calendar': "Sync",
        'download_button': "Download",
        'weekly_overview': "Week",
        'share_set_title': "Deel set '{name}'",
        'share_with_email': "Deel met e-mailadres",
        'error_cannot_share_with_self': "Je kunt geen set met jezelf delen.",
        'error_user_not_found': "Gebruiker met e-mail {email} niet gevonden.",
        'share_success': "Set succesvol gedeeld met {email}!",
        'error_share_failed': "Delen van de set is mislukt.",
        'study_again_button': "Opnieuw Leren",
        'registration_goal_title': 'Wat is je belangrijkste doel?',
        'goal_higher_grades': 'Hogere cijfers halen',
        'goal_be_organized': 'Beter georganiseerd zijn',
        'goal_better_planning': 'Beter kunnen plannen',
        'goal_less_stress': 'Minder stress ervaren',
        'registration_almost_there': 'Bijna klaar!',
        'ai_system_instruction': "Jij bent een extreem intelligente en proactieve studie-assistent genaamd {botName}. Je primaire doel is om de agenda en studieplanning van de gebruiker, {userName}, zo efficiënt mogelijk te beheren. Daarnaast ben je ook een deskundige tutor: je kunt complexe onderwerpen uitleggen, samenvattingen geven, en helpen met huiswerkvragen. Wees altijd vriendelijk, ondersteunend en proactief. Gebruik af en toe een emoji om een vriendelijke toon toe te voegen, maar overdrijf niet. Je spreekt de taal van de gebruiker.\n**BELANGRIJKE REGELS:**\n1.  **Proactief Plannen:** Lees de input van de gebruiker zorgvuldig. Identificeer direct afspraken, taken en hun tijden. Gebruik de `addCalendarEvent` functie om ze automatisch in de agenda te zetten.\n2.  **Vakken:** Het `subject` MOET EEN van de volgende zijn: {subjects}. Als het niet duidelijk is, vraag dan om verduidelijking of kies 'algemeen'.\n3.  **Functie-oproepen:** Roep de functies (`addCalendarEvent`, `removeCalendarEvent`) aan wanneer nodig, maar geef ALTIJD een bevestigende, menselijke reactie nadat de tool-output is ontvangen. Bijvoorbeeld: \"Oké, ik heb [evenement] voor je ingepland!\" of \"Ik kon [evenement] niet vinden, kun je de datum controleren?\".\n4.  **Geen Aannames:** Als de input onduidelijk is, vraag om opheldering. Voeg niet zomaar iets toe. Vraag bijvoorbeeld: \"Welk vak hoort bij deze toets?\"\n5.  **Studieplanners:** Je hebt toegang tot de studieplanners van de gebruiker. Gebruik `getStudyPlans` om een overzicht te krijgen en `getStudyPlanDetails` om de details van een specifiek plan te zien. Wees proactief: als een gebruiker vraagt \"wat moet ik vandaag leren?\", controleer dan de studieplanners.\n6.  **Algemene Vragen:** Als de vraag niet over planning gaat, beantwoord deze dan als een behulpzame studiecoach.\n7.  **Wiskundige Notatie:** Vermijd het gebruik van LaTeX of complexe wiskundige notaties zoals `\\frac{2\\pi}{3}`. Gebruik eenvoudige, platte tekstweergaven zoals 'x^2' of 'cos(2*pi/3)'.",
        'verify_user_button': 'Verifieer',
        'confirm_verify_user': 'Weet je zeker dat je {name} wilt verifiëren?',
        'user_verified_success': 'Gebruiker succesvol geverifieerd.',
        'error_user_verify_failed': 'Kon gebruiker niet verifiëren.',
        'session_in_progress': 'Sessie Bezig',
        'resume_session_prompt': 'Je hebt een onafgemaakte studiesessie. Wil je doorgaan?',
        'resume_button': 'Ja, ga door',
        'start_new_button': 'Nee, start opnieuw',
        'select_and_combine': 'Selecteer & Combineer',
        'combine_and_study': 'Combineer & Studeer',
        'exit_session': 'Sessie verlaten',
        'exit_session_confirm': 'Weet je zeker dat je de sessie wilt verlaten?',
        'study_star_count': '{count} Sterren',
        'combined_set_name': 'Gecombineerde set ({count} sets)',
        'error_select_min_two_sets': 'Selecteer ten minste 2 sets om te combineren.',
        'session_summary_title': 'Sessierapport',
        'time_spent': 'Tijdsduur',
        'correct_answers': 'Goede antwoorden',
        'incorrect_answers': 'Foute antwoorden',
        'your_answer': 'Jouw antwoord',
        'correct_answer': 'Correcte antwoord',
        'practice_incorrect': 'Oefen foute antwoorden',
        'create_set_from_incorrect': 'Maak set van foute antwoorden',
        'no_incorrect_answers': 'Perfect! Geen foute antwoorden om te oefenen.',
        'select_at_least_one_card': 'Selecteer ten minste één kaart om te oefenen.',
        'new_set_name_prompt': 'Voer een naam in voor de nieuwe set met foute antwoorden:',
        'new_set_created_success': 'Nieuwe set "{name}" succesvol aangemaakt!',
        'ai_checking_answer': 'Antwoord controleren...',
        'ai_feedback_correct': 'Correct! De AI is het ermee eens.',
        'ai_feedback_incorrect': 'Niet helemaal. Het juiste antwoord is "{correct_answer}".',
        'error_ai_check_failed': 'AI-controle mislukt. Probeer het opnieuw.',
        'submit_answer': 'Controleer antwoord',
        'flashcards_creating_message': 'Flashcards aan het maken...',
        'stars_earned_title': 'Verdiende Sterren',
        'error_sync_calendar_title': 'Fout bij Synchroniseren',
        'error_sync_calendar_description': "Kon de agenda '{name}' niet ophalen. Controleer de iCal-link en je internetverbinding. Foutdetails: {error}",
        'flashcard_ai_topic_label': "Onderwerp/Titel (Optioneel)",
        'flashcard_ai_topic_placeholder': "bv. Biologie - Hoofdstuk 2: Cellen",
        'shared_by': 'Gedeeld door {name}',
        'notification_flashcard_share_title': 'Nieuwe flashcard set gedeeld!',
        'notification_flashcard_share_text': '{name} heeft de set "{setName}" ({subject}) met je gedeeld.',
        'notification_plan_share_title': 'Nieuw studieplan gedeeld!',
        'notification_plan_share_text': "{name} heeft het plan '{planName}' met je gedeeld.",
        'share_plan_title': "Deel plan '{title}'",
        'share_plan_success': "Plan succesvol gedeeld met {email}!",
        'error_share_plan_failed': "Delen van het plan is mislukt.",
        'downloading_and_started': 'Download gestart...',
        'download_agenda': 'Agenda Downloaden',
        'download_weeks_label': 'Download voor de komende',
        'download_format_label': 'Kies een formaat',
        'sync_calendar_title': 'Agenda Synchroniseren',
        'sync_calendar_desc': 'Voeg een externe agenda (zoals van school) toe via een iCal-link. De evenementen verschijnen automatisch in je StudyBox-agenda.',
        'get_ical_link': 'Hoe kom ik aan een iCal-link?',
        'how_to_get_link': 'De meeste rooster-apps (Google, Apple, Magister, etc.) bieden een optie om je agenda te exporteren of te delen via een "publieke" of "geheime" iCal-URL. Klik op je provider voor een handleiding:',
        'sync_calendar_tutorial_google': 'https://support.google.com/calendar/answer/37648?hl=nl',
        'sync_calendar_tutorial_apple': 'https://support.apple.com/nl-nl/guide/calendar/icl1022/mac',
        'sync_calendar_tutorial_teams': 'https://support.microsoft.com/nl-nl/office/je-agenda-in-microsoft-teams-bekijken-53E4249A-591A-450C-8A62-7B52F2C55355',
        'sync_calendar_tutorial_canvas': 'https://community.canvaslms.com/t5/Student-Guide/How-do-I-subscribe-to-the-Calendar-feed-using-an-iCal-link-as/ta-p/521',
        'sync_calendar_tutorial_magister': 'https://www.google.com/search?q=magister+agenda+ical+link',
        'paste_ical_link': 'Voeg een nieuwe agenda toe',
        'calendar_name': 'Naam van agenda (bv. Schoolrooster)',
        'select_provider': 'Kies je provider (optioneel)',
        'calendar_url': 'iCal URL (moet eindigen op .ics)',
        'save_calendar': 'Agenda Opslaan',
        'synced_calendars': 'Gesynchroniseerde Agenda\'s',
        'no_synced_calendars': 'Je hebt nog geen agenda\'s gesynchroniseerd.',
        'activity_type_file': 'Bestand',
        'activity_type_note': 'Notitie',
        'activity_type_plan': 'Studieplan',
        'activity_type_set': 'Flashcards'
    },
    en: {
        'tasks_for_today': "Today's Tasks",
        'due_date': 'Due Date',
        'recurring_daily': 'Repeat daily',
        'no_tasks_for_today': "No tasks for today. Great job!",
        'todo_daily_refresh_note': 'This list refreshes daily. Completed recurring tasks will reappear.',
        'error_reauth_failed': 'Re-authentication failed. Please check your password.',
        'reauth_modal_title': 'Authentication Required',
        'reauth_modal_description': 'Please enter your password again to continue.',
        'password': 'Password',
        'cancel_button': 'Cancel',
        'confirm_delete_account_button': 'Yes, delete account',
        'reauth_modal_title_cleanup': 'Confirm Account Cleanup',
        'reauth_modal_description_cleanup': 'Enter your password to confirm you want to delete all your data.',
        'confirm_cleanup_account_button': 'Yes, clean up data',
        'reauth_modal_title_clear_calendar': 'Confirm Clear Calendar',
        'reauth_modal_description_clear_calendar': 'Enter your password to confirm you want to delete all calendar events.',
        'confirm_clear_calendar_button': 'Yes, clear calendar',
        'clear_calendar_progress': 'Clearing your calendar...',
        'success_calendar_cleared': 'Your calendar has been successfully cleared.',
        'error_calendar_clear_failed': 'Failed to clear the calendar.',
        'app_back_online_message': 'You are back online.',
        'app_offline_message': 'You are currently offline.',
        'confirm_logout': 'Are you sure you want to log out?',
        'error_save_settings_failed': 'Could not save settings.',
        'error_failed_to_save_admin_settings': 'Could not save admin settings.',
        'profile_picture_upload_success': 'Profile picture updated successfully.',
        'error_profile_pic_upload_failed': 'Could not upload profile picture.',
        'cleanup_account_progress': 'Cleaning up your account data...',
        'success_account_cleaned': 'Your account data has been successfully cleaned up.',
        'error_account_cleanup_failed': 'Account cleanup failed.',
        'deleting_account_progress': 'Deleting account...',
        'success_account_deleted': 'Your account has been successfully deleted.',
        'error_account_deletion_failed': 'Account deletion failed.',
        'error_admin_login_failed': 'Admin login failed.',
        'guest_fallback_name': 'Guest',
        'error_account_disabled': 'This account has been disabled.',
        'streak_lost_notification_title': 'Streak lost!',
        'streak_lost_notification_text': 'You had a streak of {count} days. Start a new one today!',
        'error_profile_load_failed': 'Could not load your profile.',
        'success_logout': 'You have been successfully logged out.',
        'share_link_copied': 'Link for "{title}" copied!',
        'error_copy_share_link': 'Could not copy the link.',
        'notifications_title': 'Notifications',
        'logout_button': 'Log out',
        'focus_session_complete': 'Focus session complete! Time for a break.',
        'break_session_complete': 'Break is over! Time to focus.',
        'feedback_reply_notification_title': 'Reply to your feedback',
        'feedback_reply_notification_text': 'You have received a reply to your feedback about "{subject}".',
        'confirm_button': 'Confirm',
        'close_button': 'Close',
        'calendar': 'Calendar',
        'extra_tools': 'Extra Tools',
        'settings': 'Settings',
        'feedback_support': 'Feedback & Support',
        'welcome_message': 'Welcome, {name}!',
        'streak_days': '{count} day streak',
        'my_subjects': 'My Subjects',
        'my_files': 'My Files',
        'notes': 'Notes',
        'error_unknown': 'An unknown error occurred.',
        'error_invalid_email': 'Invalid email address.',
        'error_invalid_credentials': 'Invalid login credentials.',
        'error_email_in_use': 'This email address is already in use.',
        'error_weak_password': 'Password must be at least 6 characters long.',
        'error_fill_current_step': 'Please fill in all fields for this step.',
        'error_select_subjects_register': 'Please select at least one subject.',
        'error_fill_all_fields': 'Please fill in all fields.',
        'error_enter_email_for_reset': 'Please enter your email to reset your password.',
        'password_reset_sent': 'A password reset email has been sent to {email}.',
        'your_name': 'Your name',
        'placeholder_name': 'e.g., John Doe',
        'email_address': 'Email address',
        'placeholder_email': 'your@email.com',
        'placeholder_password': '••••••••',
        'school_name': 'School name',
        'class_name': 'Class',
        'education_level': 'Education level',
        'select_level': 'Select your level',
        'select_subjects': 'Select your subjects',
        'select_your_avatar': 'Choose your avatar',
        'customize_ai_title': 'Customize your AI Assistant',
        'bot_name_placeholder': 'Name of your AI Bot',
        'select_bot_avatar': 'Choose an avatar for your bot',
        'back_button': 'Back',
        'next_button': 'Next',
        'saving': 'Saving...',
        'register_account': 'Create Account',
        'register_title': 'Register',
        'login_title': 'Log In',
        'login_button': 'Log In',
        'login_in_progress': 'Logging in...',
        'already_account': 'Already have an account? Log in',
        'no_account_register': 'No account yet? Register here',
        'forgot_password': 'Forgot password?',
        'success_registration': 'Registration successful! Please check your email to verify your account, then log in.',
        'your_subjects': 'Your Subjects',
        'search_subjects_placeholder': 'Search your subjects...',
        'profile_incomplete_message': 'You haven\'t selected any subjects yet.',
        'go_to_settings_message': 'Go to settings to complete your profile.',
        'no_subjects_found_search': 'No subjects found matching your search.',
        'todays_agenda_title': "Today's Agenda",
        'no_events_today': 'No events for today.',
        'go_to_calendar': 'Go to the full calendar',
        'recent_files_title': 'Recent Files',
        'recent_activities_title': 'Recent Activities',
        'no_recent_files': 'No files uploaded yet.',
        'no_recent_activity': 'No recent activity yet.',
        'view_button': 'View',
        'error_guest_action_not_allowed': 'Guests cannot perform this action.',
        'error_enter_file_title': 'Please enter a title for the file.',
        'error_select_file_to_upload': 'Please select a file to upload.',
        'success_file_added': 'File added successfully.',
        'error_add_file_failed': 'Could not add file: {message}',
        'error_select_files_delete': 'Please select files to delete.',
        'confirm_delete_files': 'Are you sure you want to delete {count} file(s)?',
        'success_files_deleted': 'File(s) deleted successfully.',
        'error_delete_file_failed': 'Could not delete file: {message}',
        'back_to_subjects': 'Back to subjects',
        'share_button': 'Share',
        'add_file_section_title': 'Add new file',
        'file_title_placeholder': 'Title of the file',
        'file_description_placeholder': 'Description (optional)',
        'uploading': 'Uploading...',
        'add_file_button': 'Add file',
        'admin_search_placeholder': 'Search by name or email...',
        'select_files_button': 'Select files',
        'no_files_found': 'No files found for this subject.',
        'ai_importer_title': "AI Import",
        'flashcard_ai_modal_title': "Generate Cards with AI",
        'flashcard_ai_modal_desc': "Paste or type your notes. The AI will convert them into question-and-answer cards.",
        'flashcard_ai_placeholder': "Concept 1: Explanation 1\nTerm 2 - Definition 2",
        'generate_button': "Generate",
        'generating': "Generating...",
        'in_progress_badge': 'IN PROGRESS',
        'tasks_completed': 'Tasks Completed',
        'study_time_minutes': 'Study Minutes',
        'flashcards_created': 'Flashcards Created',
        'todays_events': "Today's Events",
        'save_all_cards': "Save All",
        'settings_sync_calendar': "Sync",
        'download_button': "Download",
        'weekly_overview': "Week",
        'event_study_plan': 'Study Plan Task',
        'add_event': "New",
        'share_set_title': "Share set '{name}'",
        'share_with_email': "Share with email address",
        'error_cannot_share_with_self': "You cannot share a set with yourself.",
        'error_user_not_found': "User with email {email} not found.",
        'share_success': "Set successfully shared with {email}!",
        'error_share_failed': "Failed to share the set.",
        'study_again_button': "Study Again",
        'registration_goal_title': 'What is your main goal?',
        'goal_higher_grades': 'Get higher grades',
        'goal_be_organized': 'Be more organized',
        'goal_better_planning': 'Improve planning',
        'goal_less_stress': 'Experience less stress',
        'registration_almost_there': 'Almost there!',
        'your_grade': 'Your Grade',
        'intro_step1_title': "Welcome to StudyBox!",
        'ai_system_instruction': "You are an extremely intelligent and proactive study assistant named {botName}. Your primary goal is to manage the user's, {userName}'s, calendar and study plans as efficiently as possible. Additionally, you are also an expert tutor: you can explain complex topics, provide summaries, and help with homework questions. Always be friendly, supportive, and proactive. Use an emoji occasionally to add a friendly touch, but do not overdo it. You speak the user's language.\n**IMPORTANT RULES:**\n1.  **Proactive Planning:** Read the user's input carefully. Immediately identify appointments, tasks, and their times. Use the `addCalendarEvent` function to automatically add them to the calendar.\n2.  **Subjects:** The `subject` MUST be ONE of the following: {subjects}. If it's unclear, ask for clarification or choose 'algemeen' (general).\n3.  **Function Calls:** Call the functions (`addCalendarEvent`, `removeCalendarEvent`) when needed, but ALWAYS provide a confirmatory, human-like response after the tool output is received. For example: \"Okay, I've scheduled [event] for you!\" or \"I couldn't find [event], can you check the date?\".\n4.  **No Assumptions:** If the input is unclear, ask for clarification. Don't just add something. For example, ask: \"Which subject does this test belong to?\"\n5.  **Study Planners:** You have access to the user's study plans. Use `getStudyPlans` to get an overview and `getStudyPlanDetails` to see the details of a specific plan. Be proactive: if a user asks \"what should I study today?\", check the study plans.\n6.  **General Questions:** If the question isn't about planning, answer it as a helpful study coach.\n7.  **Mathematical Notation:** Avoid using LaTeX or complex mathematical notations like `\\frac{2\\pi}{3}`. Use simple, plain text representations like 'x^2' or 'cos(2*pi/3)'.",
        'ai_chat_welcome': 'Hello {userName}! I am {botName}, your personal study assistant. How can I help you today?',
        'no_specific_task_option': 'No task selected',
        'chat_history_title': 'Chat History',
        'new_chat': 'New Chat',
        'error_generating_title': 'Could not generate a title.',
        'verify_user_button': 'Verify',
        'confirm_verify_user': 'Are you sure you want to verify {name}?',
        'user_verified_success': 'User successfully verified.',
        'error_user_verify_failed': 'Failed to verify user.',
        'session_in_progress': 'Session in Progress',
        'resume_session_prompt': 'You have an unfinished study session. Would you like to resume?',
        'resume_button': 'Yes, Resume',
        'start_new_button': 'No, Start New',
        'select_and_combine': 'Select & Combine',
        'combine_and_study': 'Combine & Study',
        'exit_session': 'Exit Session',
        'exit_session_confirm': 'Are you sure you want to exit the session?',
        'study_star_count': '{count} Stars',
        'combined_set_name': 'Combined Set ({count} sets)',
        'error_select_min_two_sets': 'Please select at least 2 sets to combine.',
        'session_summary_title': 'Session Report',
        'time_spent': 'Time Spent',
        'correct_answers': 'Correct Answers',
        'incorrect_answers': 'Incorrect Answers',
        'your_answer': 'Your Answer',
        'correct_answer': 'Correct Answer',
        'practice_incorrect': 'Practice Incorrect',
        'create_set_from_incorrect': 'Create Set from Incorrect',
        'no_incorrect_answers': 'Perfect! No incorrect answers to practice.',
        'select_at_least_one_card': 'Select at least one card to practice.',
        'new_set_name_prompt': 'Enter a name for the new set of incorrect answers:',
        'new_set_created_success': 'New set "{name}" created successfully!',
        'ai_checking_answer': 'Checking answer...',
        'ai_feedback_correct': 'Correct! The AI agrees.',
        'ai_feedback_incorrect': 'Not quite. The correct answer is "{correct_answer}".',
        'error_ai_check_failed': 'AI check failed. Please try again.',
        'submit_answer': 'Submit Answer',
        'flashcards_creating_message': 'Creating flashcards...',
        'stars_earned_title': 'Stars Earned',
        'error_sync_calendar_title': 'Sync Error',
        'error_sync_calendar_description': "Could not fetch the calendar '{name}'. Please check the iCal link and your internet connection. Error details: {error}",
        'flashcard_ai_topic_label': "Topic/Title (Optional)",
        'flashcard_ai_topic_placeholder': "e.g., Biology - Chapter 2: Cells",
        'shared_by': 'Shared by {name}',
        'notification_flashcard_share_title': 'New flashcard set shared!',
        'notification_flashcard_share_text': '{name} has shared the set "{setName}" ({subject}) with you.',
        'notification_plan_share_title': 'New study plan shared!',
        'notification_plan_share_text': "{name} has shared the plan '{planName}' with you.",
        'share_plan_title': "Share plan '{title}'",
        'share_plan_success': "Plan successfully shared with {email}!",
        'error_share_plan_failed': "Failed to share the plan.",
        'downloading_and_started': 'Download started...',
        'download_agenda': 'Download Calendar',
        'download_weeks_label': 'Download for the next',
        'download_format_label': 'Choose a format',
        'sync_calendar_title': 'Sync Calendar',
        'sync_calendar_desc': 'Add an external calendar (like from school) via an iCal link. The events will automatically appear in your StudyBox calendar.',
        'get_ical_link': 'How do I get an iCal link?',
        'how_to_get_link': 'Most scheduling apps (Google, Apple, Magister, etc.) provide an option to export or share your calendar via a "public" or "secret" iCal URL. Click your provider for a guide:',
        'sync_calendar_tutorial_google': 'https://support.google.com/calendar/answer/37648?hl=en',
        'sync_calendar_tutorial_apple': 'https://support.apple.com/guide/calendar/icl1022/mac',
        'sync_calendar_tutorial_teams': 'https://support.microsoft.com/en-us/office/view-your-calendar-in-microsoft-teams-53E4249A-591A-450C-8A62-7B52F2C55355',
        'sync_calendar_tutorial_canvas': 'https://community.canvaslms.com/t5/Student-Guide/How-do-I-subscribe-to-the-Calendar-feed-using-an-iCal-link-as/ta-p/521',
        'sync_calendar_tutorial_magister': 'https://www.google.com/search?q=magister+calendar+ical+link',
        'paste_ical_link': 'Add a new calendar',
        'calendar_name': 'Calendar Name (e.g., School Schedule)',
        'select_provider': 'Select your provider (optional)',
        'calendar_url': 'iCal URL (must end in .ics)',
        'save_calendar': 'Save Calendar',
        'synced_calendars': 'Synced Calendars',
        'no_synced_calendars': 'You haven\'t synced any calendars yet.',
        'activity_type_file': 'File',
        'activity_type_note': 'Note',
        'activity_type_plan': 'Study Plan',
        'activity_type_set': 'Flashcards'
    }
};