// In dit bestand kun je de links naar je avatars plaatsen.
// Vervang de onderstaande voorbeelden door de 20 links die je hebt.
// Zorg ervoor dat elke link een string is, tussen aanhalingstekens, en gescheiden door een komma.

// FIX: Added missing exports to resolve import errors.
export const defaultHomeLayout: string[] = ['subjects', 'agenda', 'files'];

export const allSubjects: string[] = [
  "nederlands", "engels", "wiskunde", "natuurkunde", "scheikunde", "biologie",
  "geschiedenis", "aardrijkskunde", "economie", "maatschappijleer",
  "frans", "duits", "latijn", "informatica", "kunst", "muziek",
  "lichamelijke_opvoeding", "ckv"
];

export const educationLevels: string[] = [
  "basisschool", "mavo", "havo", "vwo", "mbo", "hbo", "wo", "anders"
];

export const availableThemeColors: string[] = ['emerald', 'blue', 'rose', 'purple', 'pink', 'indigo', 'teal', 'amber'];

export const availableFonts: { id: string, name: string, className: string }[] = [
    { id: 'inter', name: 'Inter', className: 'font-inter' },
    { id: 'poppins', name: 'Poppins', className: 'font-poppins' },
    { id: 'lato', name: 'Lato', className: 'font-lato' },
    { id: 'roboto-slab', name: 'Roboto Slab', className: 'font-roboto-slab' },
    { id: 'lora', name: 'Lora', className: 'font-lora' },
];

export const subjectDisplayTranslations: { [lang: string]: { [key: string]: string } } = {
  nl: {
    // Subjects
    "nederlands": "Nederlands", "engels": "Engels", "wiskunde": "Wiskunde", "natuurkunde": "Natuurkunde",
    "scheikunde": "Scheikunde", "biologie": "Biologie", "geschiedenis": "Geschiedenis", "aardrijkskunde": "Aardrijkskunde",
    "economie": "Economie", "maatschappijleer": "Maatschappijleer", "frans": "Frans", "duits": "Duits",
    "latijn": "Latijn", "informatica": "Informatica", "kunst": "Kunst", "muziek": "Muziek",
    "lichamelijke_opvoeding": "Lichamelijke Opvoeding", "ckv": "CKV", "algemeen": "Algemeen",
    // Education levels
    "basisschool": "Basisschool", "mavo": "MAVO", "havo": "HAVO", "vwo": "VWO",
    "mbo": "MBO", "hbo": "HBO", "wo": "WO", "anders": "Anders"
  },
  en: {
    // Subjects
    "nederlands": "Dutch", "engels": "English", "wiskunde": "Mathematics", "natuurkunde": "Physics",
    "scheikunde": "Chemistry", "biologie": "Biology", "geschiedenis": "History", "aardrijkskunde": "Geography",
    "economie": "Economics", "maatschappijleer": "Social Studies", "frans": "French", "duits": "German",
    "latijn": "Latin", "informatica": "Informatics", "kunst": "Art", "muziek": "Music",
    "lichamelijke_opvoeding": "Physical Education", "ckv": "Cultural and Artistic Education", "algemeen": "General",
    // Education levels
    "basisschool": "Primary School", "mavo": "VMBO", "havo": "HAVO", "vwo": "VWO",
    "mbo": "MBO", "hbo": "HBO", "wo": "University", "anders": "Other"
  }
};

export const translations: { [lang: string]: { [key: string]: string } } = {
    nl: {
        'error_reauth_failed': 'Herauthenticatie mislukt. Controleer je wachtwoord.',
        'reauth_modal_title': 'Authenticatie vereist',
        'reauth_modal_description': 'Voer je wachtwoord opnieuw in om door te gaan.',
        'password': 'Wachtwoord',
        'cancel_button': 'Annuleren',
        'confirm_delete_account_button': 'Ja, verwijder account',
        'reauth_modal_title_cleanup': 'Account opschonen bevestigen',
        'reauth_modal_description_cleanup': 'Voer je wachtwoord in om te bevestigen dat je alle gegevens wilt verwijderen.',
        'confirm_cleanup_account_button': 'Ja, schoon gegevens op',
        'reauth_modal_title_clear_calendar': 'Agenda leegmaken bevestigen',
        'reauth_modal_description_clear_calendar': 'Voer je wachtwoord in om te bevestigen dat je alle agenda-items wilt verwijderen.',
        'confirm_clear_calendar_button': 'Ja, maak agenda leeg',
        'clear_calendar_progress': 'Bezig met het leegmaken van je agenda...',
        'success_calendar_cleared': 'Je agenda is succesvol leeggemaakt.',
        'error_calendar_clear_failed': 'Het leegmaken van de agenda is mislukt.',
        'app_back_online_message': 'Je bent weer online.',
        'app_offline_message': 'Je bent momenteel offline.',
        'confirm_logout': 'Weet je zeker dat je wilt uitloggen?',
        'error_save_settings_failed': 'Kon instellingen niet opslaan.',
        'error_failed_to_save_admin_settings': 'Kon admin-instellingen niet opslaan.',
        'profile_picture_upload_success': 'Profielfoto succesvol bijgewerkt.',
        'error_profile_pic_upload_failed': 'Kon profielfoto niet uploaden.',
        'cleanup_account_progress': 'Bezig met het opschonen van je accountgegevens...',
        'success_account_cleaned': 'Je accountgegevens zijn succesvol opgeschoond.',
        'error_account_cleanup_failed': 'Het opschonen van het account is mislukt.',
        'deleting_account_progress': 'Account wordt verwijderd...',
        'success_account_deleted': 'Je account is succesvol verwijderd.',
        'error_account_deletion_failed': 'Het verwijderen van het account is mislukt.',
        'error_admin_login_failed': 'Inloggen als admin mislukt.',
        'guest_fallback_name': 'Gast',
        'error_account_disabled': 'Dit account is uitgeschakeld.',
        'streak_lost_notification_title': 'Streak verbroken!',
        'streak_lost_notification_text': 'Je had een streak van {count} dagen. Begin vandaag een nieuwe!',
        'error_profile_load_failed': 'Kon je profiel niet laden.',
        'success_logout': 'Je bent succesvol uitgelogd.',
        'share_link_copied': 'Link voor "{title}" gekopieerd!',
        'error_copy_share_link': 'Kon de link niet kopiëren.',
        'notifications_title': 'Notificaties',
        'logout_button': 'Uitloggen',
        'focus_session_complete': 'Focus sessie voltooid! Tijd voor een pauze.',
        'break_session_complete': 'Pauze is voorbij! Tijd om te focussen.',
        'feedback_reply_notification_title': 'Antwoord op je feedback',
        'feedback_reply_notification_text': 'Je hebt een antwoord ontvangen op je feedback over "{subject}".',
        'confirm_button': 'Bevestigen',
        'close_button': 'Sluiten',
        'calendar': 'Agenda',
        'extra_tools': 'Extra Tools',
        'settings': 'Instellingen',
        'feedback_support': 'Feedback & Support',
        'welcome_message': 'Welkom, {name}!',
        'streak_days': '{count} dagen streak',
        'my_subjects': 'Mijn Vakken',
        'notes': 'Notities',
        'error_unknown': 'Er is een onbekende fout opgetreden.',
        'error_invalid_email': 'Ongeldig e-mailadres.',
        'error_invalid_credentials': 'Ongeldige inloggegevens.',
        'error_email_in_use': 'Dit e-mailadres is al in gebruik.',
        'error_weak_password': 'Wachtwoord moet minimaal 6 tekens lang zijn.',
        'error_fill_current_step': 'Vul alle velden van deze stap in.',
        'error_select_subjects_register': 'Selecteer ten minste één vak.',
        'error_fill_all_fields': 'Vul alle velden in.',
        'error_enter_email_for_reset': 'Voer je e-mailadres in om je wachtwoord opnieuw in te stellen.',
        'password_reset_sent': 'Een e-mail voor het opnieuw instellen van je wachtwoord is verzonden naar {email}.',
        'your_name': 'Jouw naam',
        'placeholder_name': 'bv. Jan Jansen',
        'email_address': 'E-mailadres',
        'placeholder_email': 'jouw@email.com',
        'placeholder_password': '••••••••',
        'school_name': 'Naam school',
        'class_name': 'Klas',
        'education_level': 'Onderwijsniveau',
        'select_level': 'Selecteer je niveau',
        'select_subjects': 'Selecteer je vakken',
        'select_your_avatar': 'Kies je avatar',
        'customize_ai_title': 'Personaliseer je AI Assistent',
        'bot_name_placeholder': 'Naam van je AI Bot',
        'select_bot_avatar': 'Kies een avatar voor je bot',
        'back_button': 'Terug',
        'next_button': 'Volgende',
        'saving': 'Opslaan...',
        'register_account': 'Account aanmaken',
        'register_title': 'Registreren',
        'login_title': 'Inloggen',
        'login_button': 'Inloggen',
        'already_account': 'Heb je al een account? Log in',
        'no_account_register': 'Nog geen account? Registreer hier',
        'forgot_password': 'Wachtwoord vergeten?',
        'success_registration': 'Registratie succesvol! Controleer je e-mail om je account te verifiëren en log daarna in.',
        'your_subjects': 'Jouw Vakken',
        'search_subjects_placeholder': 'Zoek je vakken...',
        'profile_incomplete_message': 'Je hebt nog geen vakken geselecteerd.',
        'go_to_settings_message': 'Ga naar instellingen om je profiel compleet te maken.',
        'no_subjects_found_search': 'Geen vakken gevonden die overeenkomen met je zoekopdracht.',
        'todays_agenda_title': "Agenda van vandaag",
        'no_events_today': 'Geen evenementen voor vandaag.',
        'go_to_calendar': 'Ga naar de volledige agenda',
        'recent_files_title': 'Recente Bestanden',
        'no_recent_files': 'Nog geen bestanden geüpload.',
        'view_button': 'Bekijk',
        'error_guest_action_not_allowed': 'Gasten kunnen deze actie niet uitvoeren.',
        'error_enter_file_title': 'Voer een titel in voor het bestand.',
        'error_select_file_to_upload': 'Selecteer een bestand om te uploaden.',
        'success_file_added': 'Bestand succesvol toegevoegd.',
        'error_add_file_failed': 'Kon bestand niet toevoegen: {message}',
        'error_select_files_delete': 'Selecteer bestanden om te verwijderen.',
        'confirm_delete_files': 'Weet je zeker dat je {count} bestand(en) wilt verwijderen?',
        'success_files_deleted': 'Bestand(en) succesvol verwijderd.',
        'error_delete_file_failed': 'Kon bestand niet verwijderen: {message}',
        'back_to_subjects': 'Terug naar vakken',
        'share_button': 'Delen',
        'add_file_section_title': 'Nieuw bestand toevoegen',
        'file_title_placeholder': 'Titel van het bestand',
        'file_description_placeholder': 'Beschrijving (optioneel)',
        'uploading': 'Uploaden...',
        'add_file_button': 'Bestand toevoegen',
        'admin_search_placeholder': 'Zoek op naam of e-mail...',
        'select_files_button': 'Selecteer bestanden',
        'no_files_found': 'Geen bestanden gevonden voor dit vak.',
        'calendar_title': 'Agenda',
        'today': 'Vandaag',
        'add_event': 'Nieuwe afspraak',
        'no_events_day': 'Geen afspraken op deze dag.',
        'edit_event': 'Afspraak bewerken',
        'event_title': 'Titel',
        'event_description': 'Beschrijving (optioneel)',
        'event_test': 'Toets',
        'event_presentation': 'Presentatie',
        'event_homework': 'Huiswerk',
        'event_oral': 'Mondeling',
        'event_other': 'Anders',
        'event_work': 'Werk',
        'event_school': 'School',
        'save_note_button': 'Opslaan',
        'add_event_button': 'Toevoegen',
        'event_subject': 'Vak',
        'event_type': 'Type',
        'delete_event_confirm': 'Weet je zeker dat je "{title}" wilt verwijderen?',
        'success_event_updated': 'Afspraak succesvol bijgewerkt.',
        'success_event_added': 'Afspraak succesvol toegevoegd.',
        'settings_title': 'Instellingen',
        'settings_account_section': 'Account',
        'settings_appearance_section': 'Weergave',
        'settings_privacy_section': 'Privacy & Gegevens',
        'settings_help_info_section': 'Help & Info',
        'profile_section': 'Profiel',
        'profile_picture_current': 'Huidige profielfoto',
        'profile_picture_upload_label': 'Wijzig je profielfoto',
        'change_avatar_button': 'Avatar wijzigen',
        'add_custom_subject': 'Eigen vak toevoegen',
        'custom_subject_placeholder': 'Naam van je vak',
        'error_subject_empty': 'Vaknaam mag niet leeg zijn.',
        'error_subject_exists': 'Dit vak bestaat al.',
        'confirm_remove_subjects_warning': 'Als je vakken deselecteert, worden gerelateerde gegevens zoals bestanden en notities mogelijk niet meer weergegeven. Weet je het zeker?',
        'success_settings_saved': 'Instellingen succesvol opgeslagen.',
        'save_profile_info_button': 'Profiel opslaan',
        'password_reset_section_title': 'Wachtwoord opnieuw instellen',
        'password_reset_section_description': 'Stuur een e-mail naar {email} met instructies om je wachtwoord opnieuw in te stellen.',
        'send_reset_email_button': 'Stuur reset e-mail',
        'error_password_reset_failed': 'Kon wachtwoord reset e-mail niet versturen.',
        'danger_zone_title': 'Gegevensbeheer',
        'cleanup_account_section_title': 'Accountgegevens opschonen',
        'cleanup_account_section_description': 'Dit verwijdert al je persoonlijke gegevens (bestanden, notities, taken, etc.) maar behoudt je account. Deze actie kan niet ongedaan worden gemaakt.',
        'cleanup_account_button': 'Gegevens opschonen',
        'clear_calendar_section_title': 'Agenda leegmaken',
        'clear_calendar_section_description': 'Dit verwijdert permanent alle afspraken uit je agenda. Deze actie kan niet ongedaan worden gemaakt.',
        'clear_calendar_button': 'Agenda leegmaken',
        'delete_account_section_title': 'Account permanent verwijderen',
        'delete_account_section_description': 'Dit zal je account en al je gegevens permanent verwijderen. Deze actie kan niet ongedaan worden gemaakt.',
        'delete_account_button': 'Account verwijderen',
        'choose_theme': 'Kies een thema',
        'font_preference': 'Kies een lettertype',
        'default': 'Standaard',
        'language_preference': 'Taalvoorkeur',
        'dutch': 'Nederlands',
        'english': 'English',
        'home_layout_title': 'Startpagina indeling',
        'home_layout_description': 'Sleep de widgets om de volgorde op je startpagina aan te passen.',
        'widget_subjects': 'Mijn Vakken',
        'widget_agenda': 'Agenda',
        'widget_files': 'Recente Bestanden',
        'notifications_settings_title': 'Notificatie-instellingen',
        'enable_notifications': 'Notificaties inschakelen',
        'privacy_policy_content': 'Jouw gegevens worden veilig opgeslagen en alleen gebruikt voor de functionaliteit van de app. We delen je gegevens nooit met derden.',
        'app_info': 'Over de app',
        'faq': 'Veelgestelde vragen',
        'version': 'Versie',
        'copyright': 'Alle rechten voorbehouden.',
        'study_timer': 'Studeertimer',
        'todo_list': 'Takenlijst',
        'flashcards': 'Flashcards',
        'select_a_subject_first': 'Selecteer eerst een vak',
        'sets_for_subject': 'Sets voor {subject}',
        'set_name_placeholder': 'Naam van de nieuwe set',
        'no_sets_found': 'Geen sets gevonden voor dit vak. Maak een nieuwe aan!',
        'cards_in_set': '{count} kaarten',
        'manage_cards': 'Beheren',
        'choose_study_mode': 'Kies een studeermodus',
        'reset_srs_progress': 'Voortgang resetten',
        'study_mode_learn_title': 'Leren (SRS)',
        'study_mode_learn_desc': 'Gebruikt Spaced Repetition om je te helpen efficiënt te leren voor de lange termijn.',
        'study_mode_cram_title': 'Stampen',
        'study_mode_cram_desc': 'Ga snel door alle kaarten heen. Ideaal voor een snelle herhaling vlak voor een toets.',
        'study_mode_mc_title': 'Multiple Choice',
        'study_mode_mc_desc': 'Test je kennis met meerkeuzevragen, willekeurig gegenereerd uit je set.',
        'start_session': 'Start sessie',
        'back_to_sets': 'Terug naar sets',
        'add_flashcard': 'Flashcards toevoegen',
        'question': 'Vraag',
        'answer': 'Antwoord',
        'add_more_rows': 'Meer rijen toevoegen',
        'flashcard_added_success': 'Flashcards succesvol opgeslagen.',
        'error_empty_flashcard': 'Voer ten minste één vraag en antwoord in.',
        'next_card': 'Volgende kaart',
        'cards_to_go': '{count} kaarten te gaan',
        'show_answer': 'Toon antwoord',
        'feedback_again': 'Opnieuw',
        'feedback_good': 'Goed',
        'no_flashcards_found': 'Geen flashcards gevonden',
        'all_cards_learned_title': 'Alles geleerd!',
        'all_cards_learned_desc': 'Goed gedaan! Je hebt alle kaarten voor deze sessie bestudeerd. Kom later terug voor herhaling.',
        'choose_other_method_button': 'Kies andere modus',
        'reset_and_start_over_button': 'Reset & Herstart',
        'session_complete': 'Sessie voltooid!',
        'your_score': 'Je score: {correct} / {total}',
        'well_done_message': 'Goed gedaan! Blijf oefenen.',
        'study_again_button': 'Nog een keer',
        'focus_session': 'Focus',
        'break_session': 'Pauze',
        'Focusing on:': 'Focus op:',
        'set_added_success': 'Set succesvol aangemaakt.',
        'confirm_delete_set': 'Weet je zeker dat je de set "{name}" en alle bijbehorende kaarten wilt verwijderen?',
        'set_deleted_success': 'Set succesvol verwijderd.',
        'error_empty_set_name': 'Naam van de set mag niet leeg zijn.',
        'reset_srs_confirm': 'Weet je zeker dat je de leervoortgang (SRS) voor deze set wilt resetten?',
        'error_flashcard_set_min_cards': 'Deze modus vereist minimaal 2 kaarten in de set.',
        'loading_cards': 'Kaarten laden...',
        'error_failed_to_load_cards': 'Kon flashcards niet laden.',
        'error_failed_to_load_sets': 'Kon sets niet laden.',
        'all_subjects_option': 'Alle vakken',
        'add_note_button': 'Nieuwe notitie',
        'edit_note': 'Notitie bewerken',
        'add_note_title_placeholder': 'Titel',
        'add_note_content_placeholder': 'Begin hier met typen...',
        'note_updated_success': 'Notitie succesvol bijgewerkt.',
        'note_added_success': 'Notitie succesvol toegevoegd.',
        'error_empty_note_title': 'Titel mag niet leeg zijn.',
        'confirm_delete_note': 'Weet je zeker dat je deze notitie wilt verwijderen?',
        'note_deleted_success': 'Notitie succesvol verwijderd.',
        'set_reminder_title': 'Herinnering instellen voor: {task}',
        'reminder_date': 'Datum',
        'reminder_time': 'Tijd',
        'save_reminder_button': 'Herinnering opslaan',
        'remove_reminder_button': 'Verwijder herinnering',
        'task_reminder_title': 'Taakherinnering',
        'error_failed_to_load_tasks': 'Kon taken niet laden.',
        'add_task_placeholder': 'Voeg een nieuwe taak toe...',
        'add_task_button': 'Toevoegen',
        'no_tasks_found': 'Geen taken gevonden. Voeg er een toe om te beginnen!',
        'task_added_success': 'Taak succesvol toegevoegd.',
        'task_updated_success': 'Taakstatus bijgewerkt.',
        'confirm_delete_task': 'Weet je zeker dat je deze taak wilt verwijderen?',
        'task_deleted_success': 'Taak succesvol verwijderd.',
        'notifications_denied_error': 'Notificaties zijn geblokkeerd. Schakel ze in via je browserinstellingen.',
        'notifications_denied_prompt': 'Je hebt geen toestemming gegeven voor notificaties. De herinnering wordt niet getoond.',
        'error_empty_task': 'Taak mag niet leeg zijn.',
        'grade_calculator_title': 'Cijfercalculator',
        'grade_name_placeholder': 'Naam toets (optioneel)',
        'grade': 'Cijfer',
        'weight': 'Weging (%)',
        'add_grade': 'Cijfer toevoegen',
        'current_average': 'Je huidige gemiddelde:',
        'goal_calculator_title': 'Doelcalculator',
        'desired_average': 'Gewenst gemiddelde',
        'future_exam_weight': 'Weging toekomstige toets (%)',
        'calculate_needed_grade': 'Bereken benodigd cijfer',
        'goal_easy_message': 'Je staat al hoger dan je doel. Goed bezig!',
        'goal_impossible_message': 'Het is wiskundig onmogelijk om je doel te halen. Het hoogst haalbare is...',
        'grade_needed_message': 'Je moet een **{grade}** halen om een **{desired_average}** te staan.',
        'admin_dashboard': 'Admin Dashboard',
        'users': 'Gebruikers',
        'broadcasts': 'Aankondigingen',
        'admin_feedback_dashboard': 'Feedback',
        'loading_data': 'Gegevens laden...',
        'last_login': 'Laatste login',
        'status': 'Status',
        'actions': 'Acties',
        'active': 'Actief',
        'disabled': 'Uitgeschakeld',
        'enable_user': 'Activeer gebruiker',
        'disable_user': 'Deactiveer gebruiker',
        'refresh_data': 'Vernieuwen',
        'confirm_disable_user': 'Weet je zeker dat je gebruiker {name} wilt deactiveren?',
        'confirm_enable_user': 'Weet je zeker dat je gebruiker {name} wilt activeren?',
        'user_status_updated': 'Gebruikersstatus succesvol bijgewerkt.',
        'error_user_status_update': 'Kon gebruikersstatus niet bijwerken.',
        'send_broadcast': 'Aankondiging versturen',
        'broadcast_title_placeholder': 'Titel',
        'broadcast_message_placeholder': 'Typ hier je bericht...',
        'sending': 'Verzenden...',
        'send_message_button': 'Verstuur bericht',
        'error_broadcast_empty': 'Titel en bericht mogen niet leeg zijn.',
        'broadcast_success': 'Aankondiging succesvol verstuurd.',
        'error_broadcast_failed': 'Kon aankondiging niet versturen.',
        'past_broadcasts': 'Eerdere aankondigingen',
        'delete_all_broadcasts': 'Alles verwijderen',
        'no_past_broadcasts': 'Geen eerdere aankondigingen.',
        'confirm_delete_all_broadcasts_and_notifications': 'Weet je zeker dat je ALLE aankondigingen en de bijbehorende notificaties voor alle gebruikers wilt verwijderen? Dit kan niet ongedaan worden gemaakt.',
        'all_broadcasts_deleted': 'Alle aankondigingen en notificaties zijn verwijderd.',
        'error_deletion_failed': 'Verwijderen mislukt.',
        'from': 'Van',
        'submitted_on': 'Ingediend op',
        'status_new': 'Nieuw',
        'status_replied': 'Beantwoord',
        'reply_to_feedback': 'Antwoord op feedback',
        'your_reply_placeholder': 'Typ je antwoord...',
        'send_reply_button': 'Verstuur antwoord',
        'reply_sent_success': 'Antwoord succesvol verstuurd.',
        'error_reply_failed': 'Kon antwoord niet versturen.',
        'admin_select_feedback': 'Selecteer een feedbackbericht om de details te bekijken en te beantwoorden.',
        'admin_streak_leaderboard': 'Streak Leaderboard',
        'no_streak_users': 'Geen gebruikers met een actieve streak.',
        'verified': 'Geverifieerd',
        'admin_appearance_settings': 'Weergave Instellingen (Admin)',
        'admin_security_settings': 'Beveiligingsinstellingen',
        'admin_pin_toggle_label': 'PIN-beveiliging bij opstarten inschakelen',
        'admin_pin_verify_title': 'PIN verificatie',
        'admin_pin_verify_desc': 'Om deze instelling te wijzigen, moet je de beveiligingsvraag beantwoorden.',
        'admin_pin_secret_question': 'What is the best anime?',
        'admin_pin_answer_placeholder': 'Jouw antwoord',
        'admin_pin_error_incorrect': 'Incorrect antwoord.',
        'no_avatar_option': 'Geen avatar',
        'avatar_selection_title': 'Kies je avatar',
        'save_avatar_button': 'Opslaan',
        'back': 'Terug',
        'mark_all_as_read': 'Markeer alles als gelezen',
        'confirm_clear_all_notifications': 'Weet je zeker dat je alle notificaties wilt verwijderen?',
        'notifications_cleared': 'Notificaties gewist.',
        'no_notifications': 'Je hebt geen nieuwe notificaties.',
        'no_notifications_disabled_title': 'Notificaties zijn uitgeschakeld',
        'no_notifications_disabled_text': 'Je ontvangt geen meldingen. Je kunt dit wijzigen in de instellingen.',
        'intro_step1_title': 'Welkom bij Schoolmaps!',
        'intro_step1_text': 'Jouw persoonlijke assistent voor school. Organiseer je bestanden, agenda en notities op één plek.',
        'intro_step2_title': 'Beheer je Agenda',
        'intro_step2_text': 'Voeg toetsen, huiswerk en deadlines toe. Mis nooit meer een belangrijke datum!',
        'intro_step3_title': 'Krachtige Tools',
        'intro_step3_text': 'Gebruik de studietimer, takenlijst en flashcards om je productiviteit te verhogen.',
        'intro_step4_title': 'Kies je Stijl',
        'intro_step4_text': 'Geef je dashboard een uniek uiterlijk dat bij jouw stijl past met verschillende thema\'s en avatars.',
        'intro_step5_title': 'Klaar om te Beginnen?',
        'intro_step5_text': 'Laten we je account aanmaken en je schoolleven organiseren!',
        'intro_finish_button': 'Aan de slag',
        'verify_email_title': 'Verifieer je e-mailadres',
        'verify_email_instructions': 'We hebben een verificatielink gestuurd naar {email}. Klik op de link om je account te activeren.',
        'verify_email_spam_check': 'Controleer ook je spamfolder als je de e-mail niet kunt vinden.',
        'verify_email_continue_button': 'Ik heb mijn e-mail geverifieerd',
        'verify_email_resend_button': 'Stuur opnieuw',
        'email_sent': 'E-mail verzonden!',
        'feedback_title': 'Feedback & Support',
        'feedback_subtitle': 'Heb je een vraag, een suggestie of een probleem gevonden? Laat het ons weten!',
        'feedback_subject_placeholder': 'Onderwerp',
        'feedback_message_placeholder': 'Jouw bericht...',
        'send_feedback_button': 'Verstuur',
        'feedback_sent_success': 'Bedankt voor je feedback!',
        'error_feedback_failed': 'Kon feedback niet versturen.',
        'your_feedback_history': 'Jouw feedbackgeschiedenis',
        'no_feedback_history': 'Je hebt nog geen feedback verzonden.',
        'error_email_not_verified': 'Je e-mailadres is nog niet geverifieerd. Controleer je e-mail en klik op de verificatielink.',
        'ai_importer_title': "Rooster Maken met AI",
        'ai_importer_description': "Plak of typ je rooster hieronder. De AI zal automatisch de afspraken voor je aanmaken. Voorbeeld: 'Volgende week maandag wiskunde om 10:00 en dinsdag een toets Engels.'",
        'analyze_button': "Analyseer Rooster",
        'analyzing': "Analyseren...",
        'review_schedule': "Controleer de Gevonden Afspraken",
        'import_for_weeks': "Importeer voor",
        'weeks': "weken",
        'days_to_import': "Dagen om te importeren",
        'import_button': "Importeer in Agenda",
        'ai_no_events_found': "De AI kon geen afspraken vinden. Probeer de tekst duidelijker te maken.",
        'importing': "Importeren...",
        'import_success': "{count} afspraken succesvol geïmporteerd!",
        'import_error': "Fout bij het importeren van afspraken.",
        'ai_parsing_error': "Fout bij het analyseren van de tekst. Controleer het formaat en probeer het opnieuw.",
        'day_monday': 'Maandag', 'day_tuesday': 'Dinsdag', 'day_wednesday': 'Woensdag',
        'day_thursday': 'Donderdag', 'day_friday': 'Vrijdag', 'day_saturday': 'Zaterdag', 'day_sunday': 'Zondag',
        'edit_text_button': 'Tekst bewerken',
        'import_and_close_button': 'Importeer en sluit',
        'progress': 'Voortgang',
        'time_spent_per_subject': 'Tijd Besteed per Vak',
        'content_per_subject': 'Inhoud per Vak',
        'total_study_time': 'Totale Studietijd',
        'total_items': 'Totaal Aantal Items',
        'hours': 'uur',
        'items': 'items',
        'no_data_for_chart': 'Nog niet genoeg gegevens om een grafiek te tonen.',
        'event_type_distribution': 'Verdeling Soort Afspraken',
        'study_planner': 'Studieplanner',
        'planner_create_your_schedule': 'Maak je persoonlijke leerschema',
        'planner_subject': 'Vak',
        'planner_select_subject': 'Kies een vak',
        'planner_topic': 'Onderwerp van de toets',
        'planner_topic_placeholder': 'bv. De Koude Oorlog',
        'planner_amount': 'Hoeveelheid leerstof',
        'planner_amount_placeholder': 'bv. Hoofdstuk 1-4, 50 pagina\'s',
        'planner_test_date': 'Datum van de toets',
        'planner_generate_button': 'Genereer Schema',
        'planner_generating': 'Schema wordt gemaakt...',
        'planner_error_title': 'Oeps, er ging iets mis',
        'planner_error_text': 'De AI kon geen schema genereren. Probeer je invoer specifieker te maken of probeer het later opnieuw.',
        'planner_result_title': 'Jouw Leerschema voor {subject}',
        'planner_start_over': 'Opnieuw beginnen',
        'planner_study_day': 'Leerdag',
        'planner_task': 'Taak',
        'planner_tip': 'Tip',
        'error_all_fields_required': 'Vul alle velden in om een schema te genereren.',
        'study_planner_title': 'Mijn Studieplanners',
        'create_new_plan': 'Nieuw Plan Maken',
        'plan_for_date': 'Plan voor {date}',
        'delete_plan_confirm': 'Weet je zeker dat je dit studieplan wilt verwijderen?',
        'confirm_delete_plans': 'Weet je zeker dat je {count} plan(nen) wilt verwijderen?',
        'plan_deleted_success': 'Studieplan succesvol verwijderd.',
        'plan_subjects': 'Vakken',
        'plan_test_date': 'Datum Toets',
        'add_subject_button': 'Vak Toevoegen',
        'remove_subject_button': 'Verwijder Vak',
        'creating_plan': 'Plan wordt gemaakt...',
        'plan_created_success': 'Je persoonlijke studieplan is gemaakt!',
        'no_plans_yet': 'Je hebt nog geen studieplanners gemaakt.',
        'no_plans_cta': 'Klik op "Nieuw Plan Maken" om te beginnen!',
        'plan_title': 'Titel van Plan',
        'plan_title_placeholder': 'bv. Voorbereiding Eindexamens',
        'view_plan': 'Bekijk Plan',
        'hide_plan': 'Verberg Plan',
        'subject': 'Vak',
        'select_button': 'Selecteren',
        'select_all_button': 'Alles selecteren',
        'delete_selected_button': 'Verwijder geselecteerde',
        'back_to_subjects_selection': 'Terug naar vakken',
        'ai_chat': 'AI Chat',
        'ai_chat_placeholder': 'Vraag iets of geef een opdracht...',
        'ai_chat_welcome': 'Hoi! Hoe kan ik je vandaag helpen met je studie?',
        'ai_system_instruction': "Jij bent een extreem intelligente en proactieve studie-assistent genaamd {botName}. Jouw doel is om de agenda van de gebruiker, {userName}, zo efficiënt mogelijk te beheren.\n**BELANGRIJKE REGELS:**\n1.  **Begroeting:** Begin elk nieuw gesprek ALTIJD met een korte, vrolijke en gevarieerde begroeting.\n2.  **Proactief Plannen:** Lees de input van de gebruiker zorgvuldig. Identificeer direct afspraken, taken en hun tijden. Gebruik de `addCalendarEvent` functie om ze automatisch in de agenda te zetten.\n3.  **Sleutelwoordherkenning:**\n    *   **Werk:** Als je \"werk\" ziet (bijv. \"ik heb van 8 tot 10 werk\"), maak een afspraak aan met `title: 'Werk'`, `type: 'work'`, en de juiste tijden. Het `subject` moet 'algemeen' zijn.\n    *   **School:** Als je \"school\" ziet (bijv. \"school van 9 tot 3\"), maak een afspraak aan met `title: 'School'`, `type: 'school'`, en de juiste tijden. `subject` is 'algemeen'.\n    *   **Huiswerk/Opdrachten:** Als je een vaknaam gevolgd door \"huiswerk\" of \"opdracht\" ziet (bijv. \"Logic and sets huiswerk\"), zet dit in de agenda. `title` is 'Huiswerk: Logic and sets', `type` is 'homework', `subject` is 'algemeen' of het bijbehorende vak als je het herkent.\n4.  **Slimme Tijdsplanning:**\n    *   **CONFLICTEN VERMIJDEN:** Plan taken zoals huiswerk of studietijd NOOIT tijdens 'School' of 'Werk' uren. Gebruik de `getCalendarEvents` functie om de planning van een dag te controleren VOORDAT je een nieuwe afspraak toevoegt.\n    *   **Logische Tijd:** Plan huiswerk standaard in de middag na schooltijd (bijv. 16:00), tenzij de gebruiker een specifieke tijd geeft.\n5.  **Datum & Tijd Conversie:** Converteer altijd datums in natuurlijke taal ('morgen', 'volgende week vrijdag') naar het strikte 'YYYY-MM-DD' formaat.\n6.  **Vakken & Afkortingen:** Herken de volgende vakken en hun afkortingen: nederlands (ne), engels (en), wiskunde (wi), natuurkunde (na), scheikunde (sk), biologie (bi), geschiedenis (gs), aardrijkskunde (ak).\n7.  **Algemene Vragen:** Als een vraag niet over planning gaat, beantwoord deze dan met je algemene kennis. Blijf kort en bondig.",
        'download_agenda': 'Agenda Downloaden',
        'download_weeks_label': 'Downloaden voor de komende',
        'download_format_label': 'Selecteer formaat',
        'download_format_apple': 'Apple Agenda (.ics)',
        'download_format_google': 'Google Agenda (.ics)',
        'download_format_text': 'Tekst (.txt)',
        'download_button': 'Downloaden',
        'downloading_and_started': 'Download gestart...',
    },
    en: {
      'error_reauth_failed': 'Re-authentication failed. Please check your password.',
      'reauth_modal_title': 'Authentication Required',
      'reauth_modal_description': 'Please enter your password again to continue.',
      'password': 'Password',
      'cancel_button': 'Cancel',
      'confirm_delete_account_button': 'Yes, delete account',
      'reauth_modal_title_cleanup': 'Confirm Account Cleanup',
      'reauth_modal_description_cleanup': 'Enter your password to confirm you want to delete all your data.',
      'confirm_cleanup_account_button': 'Yes, clean up data',
      'reauth_modal_title_clear_calendar': 'Confirm Clear Calendar',
      'reauth_modal_description_clear_calendar': 'Enter your password to confirm you want to delete all calendar events.',
      'confirm_clear_calendar_button': 'Yes, clear calendar',
      'clear_calendar_progress': 'Clearing your calendar...',
      'success_calendar_cleared': 'Your calendar has been successfully cleared.',
      'error_calendar_clear_failed': 'Failed to clear the calendar.',
      'app_back_online_message': 'You are back online.',
      'app_offline_message': 'You are currently offline.',
      'confirm_logout': 'Are you sure you want to log out?',
      'error_save_settings_failed': 'Could not save settings.',
      'error_failed_to_save_admin_settings': 'Could not save admin settings.',
      'profile_picture_upload_success': 'Profile picture updated successfully.',
      'error_profile_pic_upload_failed': 'Could not upload profile picture.',
      'cleanup_account_progress': 'Cleaning up your account data...',
      'success_account_cleaned': 'Your account data has been successfully cleaned up.',
      'error_account_cleanup_failed': 'Account cleanup failed.',
      'deleting_account_progress': 'Deleting account...',
      'success_account_deleted': 'Your account has been successfully deleted.',
      'error_account_deletion_failed': 'Account deletion failed.',
      'error_admin_login_failed': 'Admin login failed.',
      'guest_fallback_name': 'Guest',
      'error_account_disabled': 'This account has been disabled.',
      'streak_lost_notification_title': 'Streak Lost!',
      'streak_lost_notification_text': 'You had a streak of {count} days. Start a new one today!',
      'error_profile_load_failed': 'Could not load your profile.',
      'success_logout': 'You have been successfully logged out.',
      'share_link_copied': 'Link for "{title}" copied!',
      'error_copy_share_link': 'Could not copy the link.',
      'notifications_title': 'Notifications',
      'logout_button': 'Log Out',
      'focus_session_complete': 'Focus session complete! Time for a break.',
      'break_session_complete': 'Break is over! Time to focus.',
      'feedback_reply_notification_title': 'Reply to your feedback',
      'feedback_reply_notification_text': 'You have received a reply to your feedback about "{subject}".',
      'confirm_button': 'Confirm',
      'close_button': 'Close',
      'calendar': 'Calendar',
      'extra_tools': 'Extra Tools',
      'settings': 'Settings',
      'feedback_support': 'Feedback & Support',
      'welcome_message': 'Welcome, {name}!',
      'streak_days': '{count} day streak',
      'my_subjects': 'My Subjects',
      'notes': 'Notes',
      'error_unknown': 'An unknown error occurred.',
      'error_invalid_email': 'Invalid email address.',
      'error_invalid_credentials': 'Invalid credentials.',
      'error_email_in_use': 'This email address is already in use.',
      'error_weak_password': 'Password must be at least 6 characters long.',
      'error_fill_current_step': 'Please fill in all fields for this step.',
      'error_select_subjects_register': 'Please select at least one subject.',
      'error_fill_all_fields': 'Please fill in all fields.',
      'error_enter_email_for_reset': 'Please enter your email to reset your password.',
      'password_reset_sent': 'A password reset email has been sent to {email}.',
      'your_name': 'Your name',
      'placeholder_name': 'e.g. John Doe',
      'email_address': 'Email address',
      'placeholder_email': 'your@email.com',
      'placeholder_password': '••••••••',
      'school_name': 'School name',
      'class_name': 'Class name',
      'education_level': 'Education level',
      'select_level': 'Select your level',
      'select_subjects': 'Select your subjects',
      'select_your_avatar': 'Choose your avatar',
      'customize_ai_title': 'Customize Your AI Assistant',
      'bot_name_placeholder': 'Name your AI Bot',
      'select_bot_avatar': 'Choose an avatar for your bot',
      'back_button': 'Back',
      'next_button': 'Next',
      'saving': 'Saving...',
      'register_account': 'Create Account',
      'register_title': 'Register',
      'login_title': 'Log In',
      'login_button': 'Log In',
      'already_account': 'Already have an account? Log in',
      'no_account_register': 'No account yet? Register here',
      'forgot_password': 'Forgot password?',
      'success_registration': 'Registration successful! Please check your email to verify your account, then log in.',
      'your_subjects': 'Your Subjects',
      'search_subjects_placeholder': 'Search your subjects...',
      'profile_incomplete_message': 'You haven\'t selected any subjects yet.',
      'go_to_settings_message': 'Go to settings to complete your profile.',
      'no_subjects_found_search': 'No subjects found matching your search.',
      'todays_agenda_title': "Today's Agenda",
      'no_events_today': 'No events for today.',
      'go_to_calendar': 'Go to full calendar',
      'recent_files_title': 'Recent Files',
      'no_recent_files': 'No files uploaded yet.',
      'view_button': 'View',
      'error_guest_action_not_allowed': 'Guests cannot perform this action.',
      'error_enter_file_title': 'Please enter a title for the file.',
      'error_select_file_to_upload': 'Please select a file to upload.',
      'success_file_added': 'File added successfully.',
      'error_add_file_failed': 'Could not add file: {message}',
      'error_select_files_delete': 'Please select files to delete.',
      'confirm_delete_files': 'Are you sure you want to delete {count} file(s)?',
      'success_files_deleted': 'File(s) deleted successfully.',
      'error_delete_file_failed': 'Could not delete file: {message}',
      'back_to_subjects': 'Back to subjects',
      'share_button': 'Share',
      'add_file_section_title': 'Add new file',
      'file_title_placeholder': 'Title of the file',
      'file_description_placeholder': 'Description (optional)',
      'uploading': 'Uploading...',
      'add_file_button': 'Add File',
      'admin_search_placeholder': 'Search by name or email...',
      'select_files_button': 'Select Files',
      'no_files_found': 'No files found for this subject.',
      'calendar_title': 'Calendar',
      'today': 'Today',
      'add_event': 'New Event',
      'no_events_day': 'No events on this day.',
      'edit_event': 'Edit Event',
      'event_title': 'Title',
      'event_description': 'Description (optional)',
      'event_test': 'Test',
      'event_presentation': 'Presentation',
      'event_homework': 'Homework',
      'event_oral': 'Oral Exam',
      'event_other': 'Other',
      'event_work': 'Work',
      'event_school': 'School',
      'save_note_button': 'Save',
      'add_event_button': 'Add',
      'event_subject': 'Subject',
      'event_type': 'Type',
      'delete_event_confirm': 'Are you sure you want to delete "{title}"?',
      'success_event_updated': 'Event updated successfully.',
      'success_event_added': 'Event added successfully.',
      'settings_title': 'Settings',
      'settings_account_section': 'Account',
      'settings_appearance_section': 'Appearance',
      'settings_privacy_section': 'Privacy & Data',
      'settings_help_info_section': 'Help & Info',
      'profile_section': 'Profile',
      'profile_picture_current': 'Current profile picture',
      'profile_picture_upload_label': 'Change your profile picture',
      'change_avatar_button': 'Change Avatar',
      'add_custom_subject': 'Add custom subject',
      'custom_subject_placeholder': 'Name of your subject',
      'error_subject_empty': 'Subject name cannot be empty.',
      'error_subject_exists': 'This subject already exists.',
      'confirm_remove_subjects_warning': 'If you deselect subjects, related data like files and notes may no longer be displayed. Are you sure?',
      'success_settings_saved': 'Settings saved successfully.',
      'save_profile_info_button': 'Save Profile',
      'password_reset_section_title': 'Reset Password',
      'password_reset_section_description': 'Send an email to {email} with instructions to reset your password.',
      'send_reset_email_button': 'Send Reset Email',
      'error_password_reset_failed': 'Could not send password reset email.',
      'danger_zone_title': 'Data Management',
      'cleanup_account_section_title': 'Clean Up Account Data',
      'cleanup_account_section_description': 'This will remove all your personal data (files, notes, tasks, etc.) but keep your account. This action cannot be undone.',
      'cleanup_account_button': 'Clean Up Data',
      'clear_calendar_section_title': 'Clear Calendar',
      'clear_calendar_section_description': 'This will permanently remove all events from your calendar. This action cannot be undone.',
      'clear_calendar_button': 'Clear Calendar',
      'delete_account_section_title': 'Delete Account Permanently',
      'delete_account_section_description': 'This will permanently delete your account and all your data. This action cannot be undone.',
      'delete_account_button': 'Delete Account',
      'choose_theme': 'Choose a theme',
      'font_preference': 'Choose a font',
      'default': 'Default',
      'language_preference': 'Language preference',
      'dutch': 'Nederlands',
      'english': 'English',
      'home_layout_title': 'Home Page Layout',
      'home_layout_description': 'Drag and drop the widgets to reorder them on your home page.',
      'widget_subjects': 'My Subjects',
      'widget_agenda': 'Agenda',
      'widget_files': 'Recent Files',
      'notifications_settings_title': 'Notification Settings',
      'enable_notifications': 'Enable notifications',
      'privacy_policy_content': 'Your data is stored securely and is only used for the functionality of the app. We never share your data with third parties.',
      'app_info': 'About the app',
      'faq': 'FAQ',
      'version': 'Version',
      'copyright': 'All rights reserved.',
      'study_timer': 'Study Timer',
      'todo_list': 'To-Do List',
      'flashcards': 'Flashcards',
      'select_a_subject_first': 'Select a subject first',
      'sets_for_subject': 'Sets for {subject}',
      'set_name_placeholder': 'Name of the new set',
      'no_sets_found': 'No sets found for this subject. Create a new one!',
      'cards_in_set': '{count} cards',
      'manage_cards': 'Manage',
      'choose_study_mode': 'Choose a study mode',
      'reset_srs_progress': 'Reset progress',
      'study_mode_learn_title': 'Learn (SRS)',
      'study_mode_learn_desc': 'Uses Spaced Repetition to help you learn efficiently for the long term.',
      'study_mode_cram_title': 'Cram',
      'study_mode_cram_desc': 'Quickly go through all cards. Ideal for a quick review before a test.',
      'study_mode_mc_title': 'Multiple Choice',
      'study_mode_mc_desc': 'Test your knowledge with multiple choice questions, randomly generated from your set.',
      'start_session': 'Start Session',
      'back_to_sets': 'Back to sets',
      'add_flashcard': 'Add Flashcards',
      'question': 'Question',
      'answer': 'Answer',
      'add_more_rows': 'Add more rows',
      'flashcard_added_success': 'Flashcards saved successfully.',
      'error_empty_flashcard': 'Please enter at least one question and answer.',
      'next_card': 'Next Card',
      'cards_to_go': '{count} cards to go',
      'show_answer': 'Show Answer',
      'feedback_again': 'Again',
      'feedback_good': 'Good',
      'no_flashcards_found': 'No flashcards found',
      'all_cards_learned_title': 'All cards learned!',
      'all_cards_learned_desc': 'Well done! You have studied all cards for this session. Come back later for review.',
      'choose_other_method_button': 'Choose other mode',
      'reset_and_start_over_button': 'Reset & Restart',
      'session_complete': 'Session Complete!',
      'your_score': 'Your score: {correct} / {total}',
      'well_done_message': 'Well done! Keep practicing.',
      'study_again_button': 'Study Again',
      'focus_session': 'Focus',
      'break_session': 'Break',
      'Focusing on:': 'Focusing on:',
      'set_added_success': 'Set created successfully.',
      'confirm_delete_set': 'Are you sure you want to delete the set "{name}" and all its cards?',
      'set_deleted_success': 'Set deleted successfully.',
      'error_empty_set_name': 'Set name cannot be empty.',
      'reset_srs_confirm': 'Are you sure you want to reset the learning progress (SRS) for this set?',
      'error_flashcard_set_min_cards': 'This mode requires at least 2 cards in the set.',
      'loading_cards': 'Loading cards...',
      'error_failed_to_load_cards': 'Could not load flashcards.',
      'error_failed_to_load_sets': 'Could not load sets.',
      'all_subjects_option': 'All subjects',
      'add_note_button': 'New Note',
      'edit_note': 'Edit Note',
      'add_note_title_placeholder': 'Title',
      'add_note_content_placeholder': 'Start typing here...',
      'note_updated_success': 'Note updated successfully.',
      'note_added_success': 'Note added successfully.',
      'error_empty_note_title': 'Title cannot be empty.',
      'confirm_delete_note': 'Are you sure you want to delete this note?',
      'note_deleted_success': 'Note deleted successfully.',
      'set_reminder_title': 'Set reminder for: {task}',
      'reminder_date': 'Date',
      'reminder_time': 'Time',
      'save_reminder_button': 'Save Reminder',
      'remove_reminder_button': 'Remove Reminder',
      'task_reminder_title': 'Task Reminder',
      'error_failed_to_load_tasks': 'Could not load tasks.',
      'add_task_placeholder': 'Add a new task...',
      'add_task_button': 'Add',
      'no_tasks_found': 'No tasks found. Add one to get started!',
      'task_added_success': 'Task added successfully.',
      'task_updated_success': 'Task status updated.',
      'confirm_delete_task': 'Are you sure you want to delete this task?',
      'task_deleted_success': 'Task deleted successfully.',
      'notifications_denied_error': 'Notifications are blocked. Please enable them in your browser settings.',
      'notifications_denied_prompt': 'You have not granted permission for notifications. The reminder will not be shown.',
      'error_empty_task': 'Task cannot be empty.',
      'grade_calculator_title': 'Grade Calculator',
      'grade_name_placeholder': 'Test name (optional)',
      'grade': 'Grade',
      'weight': 'Weight (%)',
      'add_grade': 'Add Grade',
      'current_average': 'Your current average:',
      'goal_calculator_title': 'Goal Calculator',
      'desired_average': 'Desired average',
      'future_exam_weight': 'Future test weight (%)',
      'calculate_needed_grade': 'Calculate needed grade',
      'goal_easy_message': 'You are already above your goal. Great job!',
      'goal_impossible_message': 'It\'s mathematically impossible to reach your goal. The highest you can get is...',
      'grade_needed_message': 'You need to get a **{grade}** to have an average of **{desired_average}**.',
      'admin_dashboard': 'Admin Dashboard',
      'users': 'Users',
      'broadcasts': 'Broadcasts',
      'admin_feedback_dashboard': 'Feedback',
      'loading_data': 'Loading data...',
      'last_login': 'Last login',
      'status': 'Status',
      'actions': 'Actions',
      'active': 'Active',
      'disabled': 'Disabled',
      'enable_user': 'Enable user',
      'disable_user': 'Disable user',
      'refresh_data': 'Refresh',
      'confirm_disable_user': 'Are you sure you want to disable user {name}?',
      'confirm_enable_user': 'Are you sure you want to enable user {name}?',
      'user_status_updated': 'User status updated successfully.',
      'error_user_status_update': 'Could not update user status.',
      'send_broadcast': 'Send Broadcast',
      'broadcast_title_placeholder': 'Title',
      'broadcast_message_placeholder': 'Type your message here...',
      'sending': 'Sending...',
      'send_message_button': 'Send Message',
      'error_broadcast_empty': 'Title and message cannot be empty.',
      'broadcast_success': 'Broadcast sent successfully.',
      'error_broadcast_failed': 'Could not send broadcast.',
      'past_broadcasts': 'Past Broadcasts',
      'delete_all_broadcasts': 'Delete All',
      'no_past_broadcasts': 'No past broadcasts.',
      'confirm_delete_all_broadcasts_and_notifications': 'Are you sure you want to delete ALL broadcasts and their corresponding notifications for all users? This cannot be undone.',
      'all_broadcasts_deleted': 'All broadcasts and notifications have been deleted.',
      'error_deletion_failed': 'Deletion failed.',
      'from': 'From',
      'submitted_on': 'Submitted on',
      'status_new': 'New',
      'status_replied': 'Replied',
      'reply_to_feedback': 'Reply to Feedback',
      'your_reply_placeholder': 'Type your reply...',
      'send_reply_button': 'Send Reply',
      'reply_sent_success': 'Reply sent successfully.',
      'error_reply_failed': 'Could not send reply.',
      'admin_select_feedback': 'Select a feedback message to view details and reply.',
      'admin_streak_leaderboard': 'Streak Leaderboard',
      'no_streak_users': 'No users with an active streak.',
      'verified': 'Verified',
      'admin_appearance_settings': 'Appearance Settings (Admin)',
      'admin_security_settings': 'Security Settings',
      'admin_pin_toggle_label': 'Enable PIN protection on startup',
      'admin_pin_verify_title': 'PIN Verification',
      'admin_pin_verify_desc': 'To change this setting, you must answer the security question.',
      'admin_pin_secret_question': 'What is the best anime?',
      'admin_pin_answer_placeholder': 'Your answer',
      'admin_pin_error_incorrect': 'Incorrect answer.',
      'no_avatar_option': 'No avatar',
      'avatar_selection_title': 'Choose your avatar',
      'save_avatar_button': 'Save',
      'back': 'Back',
      'mark_all_as_read': 'Mark all as read',
      'confirm_clear_all_notifications': 'Are you sure you want to clear all notifications?',
      'notifications_cleared': 'Notifications cleared.',
      'no_notifications': 'You have no new notifications.',
      'no_notifications_disabled_title': 'Notifications are disabled',
      'no_notifications_disabled_text': 'You will not receive any alerts. You can change this in settings.',
      'intro_step1_title': 'Welcome to Schoolmaps!',
      'intro_step1_text': 'Your personal assistant for school. Organize your files, calendar, and notes in one place.',
      'intro_step2_title': 'Manage Your Calendar',
      'intro_step2_text': 'Add tests, homework, and deadlines. Never miss an important date again!',
      'intro_step3_title': 'Powerful Tools',
      'intro_step3_text': 'Use the study timer, to-do list, and flashcards to boost your productivity.',
      'intro_step4_title': 'Choose Your Style',
      'intro_step4_text': 'Give your dashboard a unique look that fits your style with different themes and avatars.',
      'intro_step5_title': 'Ready to Get Started?',
      'intro_step5_text': 'Let\'s create your account and start organizing your school life!',
      'intro_finish_button': 'Get Started',
      'verify_email_title': 'Verify Your Email',
      'verify_email_instructions': 'We sent a verification link to {email}. Click the link to activate your account.',
      'verify_email_spam_check': 'Also check your spam folder if you can\'t find the email.',
      'verify_email_continue_button': 'I have verified my email',
      'verify_email_resend_button': 'Resend email',
      'email_sent': 'Email sent!',
      'feedback_title': 'Feedback & Support',
      'feedback_subtitle': 'Have a question, a suggestion, or found an issue? Let us know!',
      'feedback_subject_placeholder': 'Subject',
      'feedback_message_placeholder': 'Your message...',
      'send_feedback_button': 'Send',
      'feedback_sent_success': 'Thanks for your feedback!',
      'error_feedback_failed': 'Could not send feedback.',
      'your_feedback_history': 'Your Feedback History',
      'no_feedback_history': 'You have not sent any feedback yet.',
      'error_email_not_verified': 'Your email address is not verified. Please check your email and click the verification link.',
      'ai_importer_title': "Create Schedule with AI",
      'ai_importer_description': "Paste or type your schedule below. The AI will automatically create the events for you. Example: 'Next week Monday math at 10:00 and Tuesday an English test.'",
      'analyze_button': "Analyze Schedule",
      'analyzing': "Analyzing...",
      'review_schedule': "Review Found Events",
      'import_for_weeks': "Import for",
      'weeks': "weeks",
      'days_to_import': "Days to import",
      'import_button': "Import to Calendar",
      'ai_no_events_found': "The AI couldn't find any events. Please try to phrase the text more clearly.",
      'importing': "Importing...",
      'import_success': "{count} events imported successfully!",
      'import_error': "Error importing events.",
      'ai_parsing_error': "Error parsing the text. Check the format and try again.",
      'day_monday': 'Monday', 'day_tuesday': 'Tuesday', 'day_wednesday': 'Wednesday',
      'day_thursday': 'Thursday', 'day_friday': 'Friday', 'day_saturday': 'Saturday', 'day_sunday': 'Sunday',
      'edit_text_button': 'Edit Text',
      'import_and_close_button': 'Import & Close',
      'progress': 'Progress',
      'time_spent_per_subject': 'Time Spent per Subject',
      'content_per_subject': 'Content per Subject',
      'total_study_time': 'Total Study Time',
      'total_items': 'Total Items',
      'hours': 'hours',
      'items': 'items',
      'no_data_for_chart': 'Not enough data to display a chart yet.',
      'event_type_distribution': 'Event Type Distribution',
      'study_planner': 'Study Planner',
      'planner_create_your_schedule': 'Create your personal study schedule',
      'planner_subject': 'Subject',
      'planner_select_subject': 'Choose a subject',
      'planner_topic': 'Topic of the test',
      'planner_topic_placeholder': 'e.g., The Cold War',
      'planner_amount': 'Amount to learn',
      'planner_amount_placeholder': 'e.g., Chapters 1-4, 50 pages',
      'planner_test_date': 'Date of the test',
      'planner_generate_button': 'Generate Schedule',
      'planner_generating': 'Generating schedule...',
      'planner_error_title': 'Oops, something went wrong',
      'planner_error_text': 'The AI could not generate a schedule. Try making your input more specific or try again later.',
      'planner_result_title': 'Your Study Schedule for {subject}',
      'planner_start_over': 'Start Over',
      'planner_study_day': 'Study Day',
      'planner_task': 'Task',
      'planner_tip': 'Tip',
      'error_all_fields_required': 'Please fill in all fields to generate a schedule.',
      'study_planner_title': 'My Study Planners',
      'create_new_plan': 'Create New Plan',
      'plan_for_date': 'Plan for {date}',
      'delete_plan_confirm': 'Are you sure you want to delete this study plan?',
      'confirm_delete_plans': 'Are you sure you want to delete {count} plan(s)?',
      'plan_deleted_success': 'Study plan deleted successfully.',
      'plan_subjects': 'Subjects',
      'plan_test_date': 'Test Date',
      'add_subject_button': 'Add Subject',
      'remove_subject_button': 'Remove Subject',
      'creating_plan': 'Creating your plan...',
      'plan_created_success': 'Your personal study plan has been created!',
      'no_plans_yet': 'You haven\'t created any study planners yet.',
      'no_plans_cta': 'Click "Create New Plan" to get started!',
      'plan_title': 'Plan Title',
      'plan_title_placeholder': 'e.g., Final Exams Prep',
      'view_plan': 'View Plan',
      'hide_plan': 'Hide Plan',
      'subject': 'Subject',
      'select_button': 'Select',
      'select_all_button': 'Select All',
      'delete_selected_button': 'Delete Selected',
      'back_to_subjects_selection': 'Back to subjects',
      'ai_chat': 'AI Chat',
      'ai_chat_placeholder': 'Ask a question or give a command...',
      'ai_chat_welcome': 'Hi there! How can I help you with your studies today?',
      'ai_system_instruction': "You are an extremely intelligent and proactive study assistant named {botName}. Your goal is to manage the user's, {userName}'s, calendar as efficiently as possible.\n**IMPORTANT RULES:**\n1.  **Greeting:** ALWAYS start every new conversation with a short, cheerful, and varied greeting.\n2.  **Proactive Planning:** Read the user's input carefully. Immediately identify appointments, tasks, and their times. Use the `addCalendarEvent` function to automatically add them to the calendar.\n3.  **Keyword Recognition:**\n    *   **Work:** If you see \"work\" (e.g., \"I have work from 8 to 10\"), create an event with `title: 'Work'`, `type: 'work'`, and the correct times. The `subject` should be 'algemeen'.\n    *   **School:** If you see \"school\" (e.g., \"school from 9 to 3\"), create an event with `title: 'School'`, `type: 'school'`, and the correct times. The `subject` is 'algemeen'.\n    *   **Homework/Assignments:** If you see a subject name followed by \"homework\" or \"assignment\" (e.g., \"Logic and sets homework\"), add it to the calendar. `title` is 'Homework: Logic and sets', `type` is 'homework', `subject` is 'algemeen' or the corresponding subject if you recognize it.\n4.  **Smart Scheduling:**\n    *   **AVOID CONFLICTS:** NEVER schedule tasks like homework or study time during 'School' or 'Work' hours. Use the `getCalendarEvents` function to check a day's schedule BEFORE adding a new event.\n    *   **Logical Time:** By default, schedule homework in the afternoon after school (e.g., 16:00), unless the user specifies a time.\n5.  **Date & Time Conversion:** Always convert natural language dates ('tomorrow', 'next Friday') to the strict 'YYYY-MM-DD' format.\n6.  **Subjects & Abbreviations:** Recognize the following subjects and their abbreviations: nederlands (ne), engels (en), wiskunde (wi), natuurkunde (na), scheikunde (sk), biologie (bi), geschiedenis (gs), aardrijkskunde (ak).\n7.  **General Questions:** If a question is not about planning, answer it using your general knowledge. Keep it short and concise.",
      'download_agenda': 'Download Calendar',
      'download_weeks_label': 'Download for the next',
      'download_format_label': 'Select format',
      'download_format_apple': 'Apple Calendar (.ics)',
      'download_format_google': 'Google Calendar (.ics)',
      'download_format_text': 'Text (.txt)',
      'download_button': 'Download',
      'downloading_and_started': 'Download started...',
    }
};